### ISSUE TITLE
Iframe Box

### ISSUE THREAD

**Issue by ghost** [First-Coder/TS3-Webinterface#1]
Wäre gut wenn ihr die Iframebox verbessert. Im Moment sieht das ganze eingebunden unschön aus. Die Fontgrösse ist echt überdimensional. 

![tsiframe](https://cloud.githubusercontent.com/assets/24642274/22199839/e092426a-e15c-11e6-97f7-558c7ada9dfb.png)

**Comment by lgund** [comment]
Schreib mir mal am besten, was du noch geändert haben willst. Bis jetzt habe ich aufgenommen, das du die Font größe anpassen magst :D


________________________________
Von: Marcel Solich <notifications@github.com>
Gesendet: Montag, 23. Januar 2017 11:14
An: First-Coder/TS3-Webinterface
Cc: Subscribed
Betreff: [First-Coder/TS3-Webinterface] Iframe Box (#1)


Wäre gut wenn ihr die Iframebox verbessert. Im Moment sieht das ganze eingebunden unschön aus. Die Fontgrösse ist echt überdimensional.

[tsiframe]<https://cloud.githubusercontent.com/assets/24642274/22199839/e092426a-e15c-11e6-97f7-558c7ada9dfb.png>

[https://cloud.githubusercontent.com/assets/24642274/22199839/e092426a-e15c-11e6-97f7-558c7ada9dfb.png]

-

**Comment by ghost** [comment]
Die Fontgrösse ist ausreichend für mich. Sollte aber eben individuell einstellbar sein. Es gibt ja auch Leute die mögen eine grössere Schrift.

Hast du für mich jetzt eine fixe Lösung für mich? Wie gesagt im Moment sieht es nicht schön aus auf meinem Board.

**Comment by lgund** [comment]
Update auf version 1.1.7-open-beta. Dort kann die Schiftgröße geändert werden ;)

**Comment by ghost** [comment]
Update ist gemacht. Wo kann ich das einstellen?

**Comment by lgund** [comment]
Schau mal beim liveviewer den iframe, sollte irgendwie sowas da stehen:

`<iframe allowtransparency="true" src="https://demo.first-coder.de/entwicklung/iframeServerView.php?port=4244&instanz=0&color=666&fontsize=1em" style="height:100%;width:100%" scrolling="auto" frameborder="0">Your Browser will not show Iframes</iframe>`

Dort einfach Fontsize ändern in z.B. 12px

**Comment by ghost** [comment]
Ah okay gefunden jetzt sieht das ganze noch unschöner aus. Weisser Rand unten. Und dann werden die Channels abgeschnitten.

zum Beispiel: 

Eingangshalle
Support 
Teamspeak

aussehen soll es aber so:

Eingangshalle
Support Teamspeak

Siehe auch den Screens

Jetzige Ansicht:

![ts_old](https://cloud.githubusercontent.com/assets/24642274/22203707/9bb74dfe-e16e-11e6-8302-ec67ff50cb3d.png)

So sollte es aussehen

![ts_new](https://cloud.githubusercontent.com/assets/24642274/22203732/b6ac9b3c-e16e-11e6-9e38-989ccc52f13c.png)

**Comment by lgund** [comment]
Kannst du mir mal den Link schicken?

**Comment by ghost** [comment]
https://www.server-msh.de

**Comment by lgund** [comment]
Sieht er so aus, als ob die Bugs zu klein ist. Es würde schon reichen, wenn man:

`@media (min-width: 1025px)
.sidebar {
    flex: 0 0 310px;
    overflow: hidden;
}`

das Flex entfernt, sprich

`@media (min-width: 1025px)
.sidebar {
    overflow: hidden;
}`

Endeffekt sieht so aus:
![bild](https://cloud.githubusercontent.com/assets/13957661/22219329/aa31fffa-e1aa-11e6-85ca-a61b0469dac8.PNG)

Mobil sieht es auch jetzt schon gut aus 👍 

> Weisser Rand unten.

Kann ich nicht bestätigen

**Comment by SERVER-MSH** [comment]
Hier schau mal da siehste den weissen Rand unten.

**Comment by lgund** [comment]
Die Seite hat den viewer nicht mehr?

**Comment by ghost** [comment]
Na klar hab ich den Viewer drinnen.

[https://www.server-msh.de/forum/index.php?board-list/](url)

**Comment by lgund** [comment]
Also wo genau stört dich das weiß? Beim laden?

**Comment by ghost** [comment]
> Beim laden?

Ja genau

**Comment by lgund** [comment]
Im update heute kommen zwei neue Parameter hinzu, der eine dient dazu den Hintergrund des Spins zu ändern. Sprich am Anfang des ladens mit dem Zahnrad. Der andere Parameter dient dazu den kompletten Hintergrund des Iframes zu ändern (dein weißen Rand). Ich hoffe das dies das Problem löst.

**Comment by ghost** [comment]
Hmm funktioniert leider nicht. Folgenden Code verwende ich.

`<iframe allowtransparency="true" src="https://meineDomain.de/iframeServerView.php?port=9987&instanz=0&color=666&bodybgcolor=transparent&spinbgcolor=transparent&fontsize=12px" style="height:100%;width:100%" scrolling="auto" frameborder="0">Your Browser will not show Iframes</iframe>`

Wenn ich ihn so benutze dann ändern sich die Hintergründe. Hier wäre es schwarz.

`<iframe allowtransparency="true" src="https://meineDomain.de/iframeServerView.php?port=9987&instanz=0&color=666&bodybgcolor=000000&spinbgcolor=000000&fontsize=12px" style="height:100%;width:100%" scrolling="auto" frameborder="0">Your Browser will not show Iframes</iframe>`

rgba Codes werden auch nicht verarbeitet.

**Comment by lgund** [comment]
Mein Fehler... Wusste nicht, dass es sich um transparent handelt. Hier hast du das Script was funktionieren wird, habe es selber getestet. Im nächsten Update, wird dies auch für alle anderen so übernommen.

[https://teamspeak.first-coder.de/fix2.zip](https://teamspeak.first-coder.de/fix2.zip)

**Comment by ghost** [comment]
Hey Igund, das ist es was ich gesucht habe. So passt es ganz Prima.
