### ISSUE TITLE
Dashboard user

### ISSUE THREAD

**Issue by osnet** [First-Coder/TS3-Webinterface#10]
Wenn Benutzer  nur für einen virtuellen server berechtigt ist, 
sieht der aber dennoch in dem komischen Kreis da die  server anderer user 
![image](https://cloud.githubusercontent.com/assets/1938728/22217033/b13d6db0-e1a1-11e6-8c5d-36a75e0290db.png)
bei mouseover auch mit details 

soltle rausgenommen werden

**Comment by lgund** [comment]
Wird in der nächsten vesion 1.1.9 behoben sein. Vielen dank für die Fehlermeldung :)
