### ISSUE TITLE
installation Issue 

### ISSUE THREAD

**Issue by lastsamurai26** [First-Coder/TS3-Webinterface#101]
## System Information
***Operating System:***
Debian 9

***Operating System Type:*** 
x64

***Interface Version:***
ver. 1.3.20-STABLE

***PHP Version, MySQL/PostgreSQL Version, Apache Version:*** 
php 7.1.18, MariaDB 10.2.15, Apache 2.4.25
***TeamSpeak/TeaSpeak Server Version:***
3.2.0 auf Linux without Database -> only internal
***Web Browser and it's version:***
Opera 53.0.2907.68

## Issue
***Reason for reporting the issue:***
can't create User

***Detailed Description:***
I have the problem that I can not create a new user over the interface. I get the message that I should enter an email. The email is a valid one

**Comment by lgund** [comment]
Hey,
Which mail did you used?

**Comment by lastsamurai26** [comment]
@gmail.com
@gmx.de 


i tried with firefox, in firefox it works but not in opera, Chrome oder Vivaldi

**Comment by lastsamurai26** [comment]
ok i found an other problem, after creating a User -> the screen is blocked by the Usercreate overlay 

<img width="767" alt="screen shot 2018-06-13 at 10 10 51" src="https://user-images.githubusercontent.com/3257844/41338582-e735a664-6ef2-11e8-810b-e2e2ba1a8128.png">

**Comment by lgund** [comment]
> @gmail.com
@gmx.de

You can find the regex in the index.php on line 229. We are using this regex `/^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/` but your mail should work. It work in my chrome also. I am a bit confused why your browser don´t do it.

> ok i found an other problem, after creating a User -> the screen is blocked by the Usercreate overlay

Did you´ve a error in your php error log?

**Comment by lastsamurai26** [comment]
ok strange i will check it later this day, with this mail again 

I can create a new Account with chrome, but the problem is only now the screen you can see before.
in Opera i will test it later this day

**Comment by lgund** [comment]
But did you find some error in the browser console or log files?

**Comment by lastsamurai26** [comment]
<img width="1667" alt="screen shot 2018-06-13 at 14 27 34" src="https://user-images.githubusercontent.com/3257844/41351203-f5d6ee80-6f15-11e8-836b-02602ff30392.png">

```
Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /var/www/vhosts/httpdocs/softwaretest/wi3/php/admin/web_admin_user.php:1) in /var/www/vhosts/httpdocs/softwaretest/wi3/php/functions/functions.php on line 125

Warning: session_start(): Cannot send session cookie - headers already sent by (output started at /var/www/vhosts/httpdocs/softwaretest/wi3/php/admin/web_admin_user.php:1) in /var/www/vhosts/httpdocs/softwaretest/wi3/php/functions/functions.php on line 125

Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /var/www/vhosts/httpdocs/softwaretest/wi3/php/admin/web_admin_user.php:1) in /var/www/vhosts/httpdocs/softwaretest/wi3/php/functions/functions.php on line 125

[13-Jun-2018 14:34:04 Europe/Berlin] PHP Notice:  Undefined index: withPk in /var/www/vhosts/httpdocs/softwaretest/wi3/php/functions/functionsSqlPost.php on line 181
[13-Jun-2018 14:34:04 Europe/Berlin] PHP Notice:  Undefined index: crypted in /var/www/vhosts/httpdocs/softwaretest/wi3/php/functions/functionsSqlPost.php on line 194
```


Same error when you go to the logs 

`Notice: Undefined variable: logAvalible in /var/www/vhostshttpdocs/softwaretest/wi3/php/admin/web_admin_logs.php on line 87`

**Comment by lgund** [comment]
That's strange... Will be the user created? Is there a line in the database table main_clients and main_clients_info?

**Comment by lastsamurai26** [comment]
sure, the user will be created and can login, but it is strange that i must reload the site to interact again with the site

**Comment by lgund** [comment]
Looks like it´s a problem from bootstrap. The easiest way will be to deactivate the backdrop effect. Can you please check if this will be work? Just go in the /php/admin/web_admin_user.php to the line 71 and change `data-backdrop="true"` to `data-backdrop="false"`.

**Comment by lastsamurai26** [comment]
![unbenann22](https://user-images.githubusercontent.com/3257844/41499771-79d7e8de-7186-11e8-9886-82571cffc3b6.PNG)
Normelly he will reload the site ?

it works but I see the created user only after reloading the page

**Comment by lgund** [comment]
Ye you should deactivate show_errors. It will just block the source. I will look in for the notice to remove them but it would be fine for now if you go into you php.ini and set display_errors to off. It will just don´t show on the site they will stay be logged. After that you will not have any problems more.

**Comment by lgund** [comment]
Is this problem solved?

**Comment by lastsamurai26** [comment]
sry, for the late answer. 

yes, it works for now. The error is no longer displayed, but still logged
