### ISSUE TITLE
Projektvorstellung

### ISSUE THREAD

**Issue by RawNetworks** [First-Coder/TS3-Webinterface#102]
Hallo,

ich würde gerne das Projekt vorstellen. Dabei würde ich gerne einen Installer schreiben, was die Installation erleichtert.
Ich würde alle Informationen verlinken in meinen Videos. Ich möchte gerne dieses Projekt unterstützen.
Ist die Interesse da?

Mfg RAW Networks - https://youtube.com/c/RawNetworksYouTube

**Comment by Bluscream** [comment]
Hmm, du hast nicht grade die beste reputation was deine "projekte" angeht. Obfuscatete bash scripts und entfernte copyright verweise ausserdem mitliefern von veralteten version statt dem ursprungsdownload sind nicht sehr vertrauenserweckend. Ein remote-update von dir und hunderte server könnten zu deinen sklaven werden. Ich rate Lukas davon ab aber am ende muss er entscheiden.

**Comment by Provokan** [comment]
Da kann ich mich nur Bluscream anschließen, 
wenn ich dass du schon Reviews zu Bots raushaust, die Cracked sind, dann Rate ich auch
nur Lukas davon ab. 

Es bringt nichts, ein Review von jemanden zu haben, der bereits sämtliche Cracks gezeigt hat.

**Comment by RawNetworks** [comment]
Hi,
ich hatte früher Cracks gezeigt. Das stimmt wohl, aber ich habe meinen Content geändert. Das SinusBot MultiScript ist ja, wenn man es richtig sieht, kein Crack. Es ist einfach nur ein Installer Script was mehrere Instanzen erstellt. Nochmal zu Bluscream. Ich hatte früher meine Scripts unverschlüsselt veröffentlicht. Leider hat fast jeder die Scripts umgeschrieben und vereinzelt verkauft. Deswegen war ich gezwungen meine Scripts leicht zu verschlüsseln. Ich baue ja dort keine richtige Verschlüsselung ein. Sie sollte nur ausreichen um die kleinen Hater davon abzuhalten, damit Geld zu verdienen.  Ich muss ja auch meine Scripts mit einem Update Server verbinden, damit sich die Scripts updaten. Zudem kann ich ein bestes Beispiel geben, wo jemand auf r4p3.net mein Script umschreibt und als seins ausgibt. Ich glaube er hieß TheHenker: https://r4p3.net/threads/teamspeak3-audiobot-installer-script-debian-ubuntu.6722/
