### ISSUE TITLE
TeaSpeak compatibility

### ISSUE THREAD

**Issue by Riddler76** [First-Coder/TS3-Webinterface#103]
***Operating System Type:*** (x86|x64)
Linux x64
***Interface Version:*** (do not use generic words like "latest" or equal, insert the number)
2.0.4 & 1.3.21

***PHP Version, MySQL/PostgreSQL Version, Apache Version:*** (do not use generic words like "latest" or equal, insert the number)
Php 7.0.30 & mysql 14.14 Distrib 5.7.23

***TeamSpeak/TeaSpeak Server Version:***
TeaSpeak 1.2.15-b9

***Web Browser and it's version:***
Firefox 60

## Issue
***Reason for reporting the issue:***

I cant connect Webinterface on TeaSpeak server.

But i can connect Temspeak server.

I create 2 instances.

FFF1 : TeaSpeak port : 10110
FFF2 : Teamspeak port : 10011

![image](https://user-images.githubusercontent.com/8199973/45038582-ca785480-b061-11e8-91dc-c1ed9056f2e6.png)

**Comment by lgund** [comment]
Can you check ifyou can login into the query console with telnet? Did this work? Or does Wolff Dev changed the telnet Syntax?

**Comment by Riddler76** [comment]
```
TeaSpeak
Welcome on the TeaSpeak ServerQuery interface.
```

Telnet is OK on 2 server.

**Comment by lgund** [comment]
did you try if `login serveradmin ****` works? That would be nice.

**Comment by razaqq** [comment]
Tested and works with teaspeak aswell. Op is using wrong user/pass

**Comment by lgund** [comment]
Then you should check if the login information are correct. You can see the login information of the interface under /config/instances.php
