### ISSUE TITLE
Make php-mysql a requirement

### ISSUE THREAD

**Issue by razaqq** [First-Coder/TS3-Webinterface#104]
## System Information
***Operating System:***
debian strech

***Operating System Type:*** (x86|x64)
x86

***Interface Version:*** (do not use generic words like "latest" or equal, insert the number)
2.0.4

***PHP Version, MySQL/PostgreSQL Version, Apache Version:*** (do not use generic words like "latest" or equal, insert the number)
7.0

***TeamSpeak/TeaSpeak Server Version:***
doesnt matter

***Web Browser and it's version:***
doesnt matter

## Issue
***Reason for reporting the issue:***
php7.0-mysql isnt a requirement.
If you try to install, you will be notified: could not find driver.
Make sure that php7.0-mysql is required, just like php7.0-zip and php7.0-soap are required.

**Comment by lgund** [comment]
That´s a very good idea. I will implment this in the comming version. :+1:

**Comment by lgund** [comment]
in the comming version will be the PDO class as requirement. But it will be also mysql or sqlite required
