### ISSUE TITLE
Benutzersteuerung auf Server : Token, Prokotoll, etc 

### ISSUE THREAD

**Issue by osnet** [First-Coder/TS3-Webinterface#11]
Existierende Tockens können nicht aus der  TS DB gelesen werden. 
wäre sinnvoll bei Wechsel von  Psychokiller auf  dieses WebUI
EDIT: 
es wird was geladen,  aber sofort kommt der Preloader und die Seite ist wieder "blank"

BenutzerRecht, kein AdminRecht

alle Unterpunkte ohne Funktion: 
![image](https://cloud.githubusercontent.com/assets/1938728/22217304/bffa9fca-e1a2-11e6-854a-cb345233cec0.png)

**Comment by lgund** [comment]
Bei mir Funktioniert alles ohne Probleme...
![token](https://cloud.githubusercontent.com/assets/13957661/22219021/74fdc680-e1a9-11e6-84f1-3ebb74e68de1.PNG)


> Existierende Tockens können nicht aus der TS DB gelesen werden.
wäre sinnvoll bei Wechsel von Psychokiller auf dieses WebUI

Werden bei mir angzeigt.... komisch :/ Gibt es hierzu irgendwelche Fehler in den logs?

**Comment by osnet** [comment]
ich werde zugespammt mit headers already sent ...   functions.php line 30

**Comment by lgund** [comment]
Das sind nur notice Meldungen. Werde ich demnächst entfernen, sollten aber keinerlei fehler sein.

**Comment by lgund** [comment]
> Existierende Tockens können nicht aus der TS DB gelesen werden.
wäre sinnvoll bei Wechsel von Psychokiller auf dieses WebUI
EDIT:
es wird was geladen, aber sofort kommt der Preloader und die Seite ist wieder "blank"

Besteht dieser Fehler überhaupt noch?

**Comment by lgund** [comment]
Gehe davon aus das auch hier der Fehler nicht mehr vorhanden ist...
