### ISSUE TITLE
Sitestyle

### ISSUE THREAD

**Issue by osnet** [First-Coder/TS3-Webinterface#12]
Die Themes sind ja schoen und gut,
Sollte aber via Admin / userCP  verwaltbar sein. 

Globales Überschrieben der Schriftstyles  waere auch  klasse. 
Andere Schriftarten sowie Grösse  frei zu wählen käme gut, 
Ich habe den Eindruck ich muss den Monitor weiter nach hintenstellen, da die fonts so gross dargestellt werden  : )

**Comment by lgund** [comment]
Man kann das theme unter Einstellungen einstellen. Die Themes besitzen viele kommentare zur einfachen Anpassung 👍

**Comment by osnet** [comment]
Einstellungen ( Globale Einstellungen )  momentan  ausserfunktion. 
ist nur ein "reloadf" der aktuellen seite ?

**Comment by lgund** [comment]
Ok das sollte nciht sein, was steht in den logs?

**Comment by lgund** [comment]
Kann es sein, dass bei dir ebenfalls soap deaktiviert ist ?

**Comment by lgund** [comment]
Ich gehe davon aus, das der Fehler behoben ist.
