### ISSUE TITLE
Änderung Startseite

### ISSUE THREAD

**Issue by ghost** [First-Coder/TS3-Webinterface#13]
So habe mir mal das Standard Theme angepasst siehe Screen.
![anpassung_ts_webinterface](https://cloud.githubusercontent.com/assets/24642274/22219845/afd25868-e1ac-11e6-8f90-160d23b08d1e.png)

So nun meine Frage. Die Box wo momentan **Mitwirkende** drin steht, kann/darf man dies ändern wenn ja wo ändere ich das ganze?

**Comment by lgund** [comment]
Ich würde es natürlich begrüßen, wenn diese nicht geändert wird. Allerdings kann ich euch davon nicht abhalten. Ändern kann man dies in der Datei web_main_main.php. Falls ein Hintergrundbild von Wallpapercave verwendet wrid, darf dieses aus rechtlichen Gründen nicht entfernt werden.

Und das (c) bitte auf keinen Fall entfernen!

**Comment by ghost** [comment]
> Und das (c) bitte auf keinen Fall entfernen!

Ist doch noch vorhanden.

Kein Problem dann lasse ich die Boxen drinne und setze darüber meine Eigenen.

**Comment by lgund** [comment]
> Ist doch noch vorhanden.

hoffe ich doch :D

> Kein Problem dann lasse ich die Boxen drinne und setze darüber meine Eigenen.

Du kannst auch News schreiben, das weißt du oder? ^^

**Comment by ghost** [comment]
> hoffe ich doch :D

Ich würde nie ein Copyright entfernen. Bin schon eine ältere Generation und weiss was sich gehört.

> Du kannst auch News schreiben, das weißt du oder? ^^

Ja weiss ich aber die Box sieht für mich ansehnlicher aus als wie die News darüber.

**Comment by lgund** [comment]
Alles klar ;).. ich denke dann sind wir hier fertig :)

#closed

**Comment by lgund** [comment]
Ich muss noch was dazu sagen, nicht das es zu einer großen Überraschung kommt :D. Das update system überschreibt alle dateien, auch die du vllt mühevoll schon angepasst hast. Daher wäre es ratsam, die dateien die du bearbeitet hattest, vor dem update abzusichern und nachträglich zu überarbeiten. Oder eben kein update zu machen, wovon ich aber abraten würde  (zumindest in der Anfangszeit)

**Comment by ghost** [comment]
Sind nur zwei css DDateien die ich geändert habe. Die sind gesichert.

**Comment by lgund** [comment]
Ich bearbeite nur die sytle.css, wenn du ein eigenes theme im ordner themes änderst bzw. erstellt, so sind diese sicher vor updates.

**Comment by ghost** [comment]
Ah okay das hab ich mal eben gemacht. Habe aber auch an der **bootstrap.css** eine Änderung für meine Bedürfnisse anpassen müssen. Wie sieht es damit aus? Wird die auch überschrieben?

**Comment by lgund** [comment]
Da dein theme style nach dem bootstrap.css geändert wurde, werden diese überschreibt. Kopiere einfach die geänderten Zeilen in dein theme rein und diese werden übernommen.


Allgemein sollte man in Framework stylesheet keine Änderungen vornehmen, da man später eventuell auf eine neue version updaten mag.

**Comment by ghost** [comment]
> Kopiere einfach die geänderten Zeilen in dein theme rein und diese werden übernommen.

Hab ich gemacht.
Jetzt fehlt mir nur noch eine CSS Klasse siehe Screen.

> Der Teamspeak Baum wird geladen

dort will ich den weißen Hintergrund transparent machen. Welche Klasse ist das? Finde sie nicht.

![teamspeakbaum-wird-geladen](https://cloud.githubusercontent.com/assets/24642274/22244437/e216161e-e22b-11e6-9f87-02ead8404d04.png)

**Comment by lgund** [comment]
Wollen wir uns morgen mal im ts treffen und das problem angehen?

**Comment by ghost** [comment]
> Wollen wir uns morgen mal im ts treffen und das problem angehen?

Oh ist es doch etwas komplizierter? 
Okay muss ich sehen hab immer zeitliche Einschränkungen da ich mehr unterwegs bin wie zu Hause. Momentan bin ich in der tiefsten Schweiz. Mache momentan alles übern Tablet.

**Comment by lgund** [comment]
> Oh ist es doch etwas komplizierter?

Ansich reicht es, wenn du die Klasse bei Bootstrap.css raus kopierst und in deinem Style einfügst. Falls es nicht geht müsste man genauer schauen warum...

**Comment by ghost** [comment]
> Ansich reicht es, wenn du die Klasse bei Bootstrap.css raus kopierst

Okay welche Klasse dafür verantwortlich ist weißt du nicht zufällig?

**Comment by lgund** [comment]
> Okay welche Klasse dafür verantwortlich ist weißt du nicht zufällig?

Das kommt drauf an wo du was geändert hast. Du meintest doch, das du was geändert hast...

**Comment by ghost** [comment]
Nein den Ladebildschirm Der Teamspeakbaum wird geladen habe ich nicht geändert. Den will ich ändern b.z.w den Background transparent machen. Momentan hat er ja einen weißen Background. Dieser wechselt dann in Grün (TS online) oder Rot (TS offline)

![teamspeakbaum-wird-geladen](https://cloud.githubusercontent.com/assets/24642274/22245949/cd343c2e-e232-11e6-9d28-101bc6f0a6b8.png)

**Comment by lgund** [comment]
Der Hintergrund ist vorher weiß, da keine definiert wurde. Wenn du das ändenr möchtest, dann musst du dem iframe im style element eine Farbe definieren.

Da wir nun inzwischen wieder beim Ifram sind und das eigentliche Thema abgeschlossen ist, sollten wir dorthin zurückwechseln :).

#1 IFRAME BOX

**Comment by ghost** [comment]
> IFRAME BOX

Okay in welcher CSS ist der Code drinnen?
