### ISSUE TITLE
Einstellungen werden nicht geöffnet

### ISSUE THREAD

**Issue by Jniklas2** [First-Coder/TS3-Webinterface#15]
Wenn ich Links in der Seitenleiste unter Globale Einstellungen auf Einstellungen klicke dann kommt nur die gleiche Seite wieder auf. In der Konsole kommt der Fehler vom verlinkten Bild. http://prnt.sc/dzh234
Nutze die Version 1.1.7-OPEN-BETA

**Comment by lgund** [comment]
Alles klar, danke erstmal für das bild :). Was sagt die php log dazu?

**Comment by Jniklas2** [comment]
[error.log.txt](https://github.com/First-Coder/TS3-Webinterface/files/726680/error.log.txt)
Hab die Datei einfach mal Hochgeladen

**Comment by lgund** [comment]
Fehler gefunden. SoapClient ist nicht definiert. Die homepage benötigt das Soap modul. Scheint wohl deaktiviert zu sein. Einfach Soap Modul aktivieren ;)

**Comment by lgund** [comment]
In der neuen Version wird eine SOAP Überprüfung vorhanden sein :)

**Comment by Jniklas2** [comment]
ok danke

**Comment by lgund** [comment]
Ist das problem behoben?

**Comment by Jniklas2** [comment]
jo klar, nochmal danke für die schnelle Hilfe
