### ISSUE TITLE
Server Admin Query Token erstellen

### ISSUE THREAD

**Issue by ntimo** [First-Coder/TS3-Webinterface#16]
Hi,
es wäre super wenn man auch Token für die Gruppe des Server Admin Query erstellen könnte. Dies sollte natürlich nur als super admin des scripts möglich sein :)

Danke,
Timo

**Comment by lgund** [comment]
Ist aus Sicherheitsgründen nicht möglich. Hab leider keine Definition für "Superadmin". Hast du dafür eine Idee?

**Comment by ntimo** [comment]
naja der Superadmin sollte der Account mit allen rechten sein, also auch dem einen super admin query token zu erstellen. Der superadmin Account ist der, der bei der installation des Scripts erstellt wurde.

**Comment by lgund** [comment]
> Der superadmin Account ist der, der bei der installation des Scripts erstellt wurde.

Dieser wird leider nicht eindeutig gespeichert.

Ich könnte höchstens bei Instanzen die Info zum vergeben der Admin Query Rechte ein Info hinterlegen, alles andere wäre Sicherheitstechnisch nicht vereinbar.

**Comment by ghost** [comment]
> Ich könnte höchstens bei Instanzen die Info zum vergeben der Admin Query Rechte ein Info hinterlegen, alles andere wäre Sicherheitstechnisch nicht vereinbar.

Das wäre nicht schlecht.

**Comment by lgund** [comment]
Ist in der neuen Version heute hinzugefügt... Sieht insgesamt so aus:

![instanz](https://cloud.githubusercontent.com/assets/13957661/22248593/93d5d98a-e23f-11e6-9c5f-d3d9c1a92307.JPG)

**Comment by ghost** [comment]
Wunderbar
