### ISSUE TITLE
Einstellungen Standardgruppen wird gespeichert oder doch wieder nicht

### ISSUE THREAD

**Issue by ghost** [First-Coder/TS3-Webinterface#17]
So habe da noch was gefunden. Nun die Frage ob es an mir liegt oder am Script. 

Standardgruppen Einstellungen Speichern ist erfolgreich siehe Screen

![speicherung](https://cloud.githubusercontent.com/assets/24642274/22253983/abdc22dc-e253-11e6-984c-21cd2b07f36b.png)

So gehe ich raus und dann wieder in die Einstellungen steht dann folgendes, siehe Screen.

![reload](https://cloud.githubusercontent.com/assets/24642274/22254025/c6458abe-e253-11e6-8d5d-72fa8691f456.png)

Scriptfehler oder Benutzerfehler?

**Comment by lgund** [comment]
Ich weiß nicht genau, wie du das hinbekommen hast... bin gerade min. dabei den Fehler nachzumachen :D kriege es einfach nicht hin :S

**Comment by ghost** [comment]
> Ich weiß nicht genau, wie du das hinbekommen hast... bin gerade min. dabei den Fehler nachzumachen :D kriege es einfach nicht hin :S

Eben ich habe nichts gemacht.

**Comment by lgund** [comment]
Schreib mir nochmal step by step wie du es geschafft hast :D

**Comment by ghost** [comment]
Ich habe nichts gemacht das ist von Anfang an da.

Schritt eins: Serverübersicht ----> Einstellungen
Schritt zwei: Unter Haupteinstellungen Standardgruppen öffnen
Schritt drei: wähle bei Servergruppe Normal aus speichern. Wird übernommen. Drücke F5 oder STRG+R zum aktualisieren der Seite und siehe da es steht folgendes drinne.

`$value) { if ($value['type'] != '2' AND $value['type'] != '0') { if($server['data']['virtualserver_default_server_group'] == $value['sgid']) { echo $value['name']; }; }; }; }; ?>`

Dort sollte aber eigentlich Guest drinne stehen oder eben was man ausgewählt hat. Oder?
Tja nur irgendwie stellt er das wieder um auf den oben geposteten Code egal welche Option ich auswähle.

**Comment by ghost** [comment]
Wenn nicht soll ich dir mal einen Account erstellen und du guckst mal?

**Comment by lgund** [comment]
> Dort sollte aber eigentlich Guest drinne stehen oder eben was man ausgewählt hat. Oder?

Jedenfalls kein Quelltext. Habe gerade eine neue Version online gestellt. Update zu dieser Version. Diese überschreibt auch den Quelltext. Vielleicht ist dann der bug weg.

**Comment by ghost** [comment]
> Vielleicht ist dann der Bug weg.

Ja jetzt passt es wunderbar.
