### ISSUE TITLE
Teamspeak Interface Musicbot

### ISSUE THREAD

**Issue by lgund** [First-Coder/TS3-Webinterface#18]
Add the musicbot into the interface:

- [X] Compile the Bot under Linux
- [X] Connect the Bot
- [X] Start the Bot
- [X] Try to Play Music
- [ ] Get Access to the API

**Comment by ntimo** [comment]
Hi, what kind of music bot will your interface support?

**Comment by ghost** [comment]
??????????????

**Comment by lgund** [comment]
It will be a open source music bot. More details will be, if the interface going into the alpha.

**Comment by lgund** [comment]
Btw. It's not written from me :)

**Comment by ghost** [comment]
Gibt es hier dies bezüglich schon neue Infos? Wird es ins TS Webinterface integriert?

**Comment by lgund** [comment]
Der Musikbot wurde nicht von mir entwickelt. Ich habe mich vor ca. 3 Monaten mit einem Entwickler getroffen und wir kamen zu dem Entschluss, eine API dazu zu entwickeln. Es handelt sich hierbei um den Audiobot von Splamy. Dieser lief vor 3 Monaten nicht mal 24 std durch, jedoch läuft er momentan sehr stabil. Er ist zwar bis heute noch nicht für ein stable release bereit, aber ich denke da fehlt nicht mehr viel. Der Bot hat einen großen Funktionsumfang, läuft auf Windows, sowie auch Linux. Noch dazu ist es ein Open Source Projekt das unter AGPL veröffentlicht ist.

Hier der Link: [https://github.com/Splamy/TS3AudioBot](https://github.com/Splamy/TS3AudioBot)

**Comment by ghost** [comment]
Danke für die ausführliche Erklärung Igund.

**Comment by Provokan** [comment]
Soweit ich weiß, bietet aber auch der Sinusbot eine API um deren Musikbot zu verwalten, dieser lässt sich auch mit Plugins erweitern (-:

**Comment by lgund** [comment]
Das ist korrekt, allerdings wollte ich ein offeneres System haben ohne Lizenz und den quatsch. Zudem ist der von Splamy Ressourcenarmer 👍

**Comment by Splamy** [comment]
> dieser lässt sich auch mit Plugins erweitern

Pluginsystem is beim TS3AudioBot auch auf dem besten Weg und seit langem sogar schon funktionabel.
Außerdem bekommt man beim TS3AB vollen Zugriff von Plugins auf die innere Botstruktur über C#. (Ja ich bin kein Fan von JavaScript :P)

**Comment by lgund** [comment]
> Ja ich bin kein Fan von JavaScript 📦 

Musste Beruflich in Javascript Objektorientiert schreiben.... Ohne Worte 👎

**Comment by lgund** [comment]
Will be forwarded to [https://github.com/First-Coder/TS3-Control](https://github.com/First-Coder/TS3-Control)
