### ISSUE TITLE
TicketBereich.txt Rechte verworfen nach Bereich Löschen

### ISSUE THREAD

**Issue by ragman104** [First-Coder/TS3-Webinterface#19]
die Datei rechte (linux) für die TicketBereich.txt werden nach dem Löschen eines Ticketbereiches zurück gesetzt, das Interface mault das auch nach kurzer zeit an das die rechte nicht mehr 766 sind für die Datei. 

Das Problem tritt auf jedenfall Reproduzierbar auf wenn man erst einen bereich Anlegt und ihn dann wieder löscht.

Gruß
Mike

**Comment by lgund** [comment]
Ich konnte das jetzt nur nochvollziehen beim Ticketbereich löschen. Bitte überschreibe unter nachfolgenden Link die Datei im Stammverzeichnis des Interfaces und schaue ob das Problem wieder auftaucht.

Link: [https://teamspeak.first-coder.de/fix3.zip](https://teamspeak.first-coder.de/fix3.zip)

**Comment by ragman104** [comment]
Hi,

Sieht Gut aus, Problem wohl beseitig. Top 👍

**Comment by lgund** [comment]
Immer wieder gern ;)
