### ISSUE TITLE
Erlauben von Starken Passwörtern

### ISSUE THREAD

**Issue by ntimo** [First-Coder/TS3-Webinterface#2]
Hi,
Es wäre super wenn man starke Kennwörter nutzen könnte wie z.b: 6wPUtsG}=V29FXZoED7XFCyR)]hdZeRnH/r74}motXhR9%X,qoJz%#682WtMPdCQ

Wenn ich dieses versuche zu nutzen bekomme ich nur einen Fehler, das dass Passwort nicht den Regeln entspricht obwohl es aus Kleinbuchstarben, Zahlen und Großbuchstarben besteht.

Danke
Timo

**Comment by lgund** [comment]
Kann an den Sonerzeichen liegen, schonmal ohne Probiert?


________________________________
Von: TimoViBritannia <notifications@github.com>
Gesendet: Montag, 23. Januar 2017 11:20
An: First-Coder/TS3-Webinterface
Cc: Subscribed
Betreff: [First-Coder/TS3-Webinterface] Erlauben von Starken Passwörtern (#2)


Hi,
Es wäre super wenn man starke Kennwörter nutzen könnte wie z.b: 6wPUtsG}=V29FXZoED7XFCyR)]hdZeRnH/r74}motXhR9%X,qoJz%#682WtMPdCQ

Wenn ich dieses versuche zu nutzen bekomme ich nur einen Fehler, das dass Passwort nicht den Regeln entspricht obwohl es aus Kleinbuchstarben, Zahlen und Großbuchstarben besteht.

Danke
Timo

-

**Comment by ntimo** [comment]
Nein, ohne habe ich es noch nicht probiert. Sekunde

**Comment by ntimo** [comment]
Auch das geht nicht, bekomme den Fehler: "Das Password muss ein Großbuchstaben, Kleinbuchstaben, sowie Zahl enthalten!"

**Comment by lgund** [comment]
Habe es bei mir im Changelog aufgenommen. Schick dir im Anhang aber schon mal die Änderung. Einfach überschreiben, dann sollte es gehen.


________________________________
Von: TimoViBritannia <notifications@github.com>
Gesendet: Montag, 23. Januar 2017 11:27
An: First-Coder/TS3-Webinterface
Cc: First-Coder; Comment
Betreff: Re: [First-Coder/TS3-Webinterface] Erlauben von Starken Passwörtern (#2)


Auch das geht nicht, bekomme den Fehler: "Das Password muss ein Großbuchstaben, Kleinbuchstaben, sowie Zahl enthalten!"

-

**Comment by lgund** [comment]
Bitte um Rückmeldung, ob alles funktioniert ;)

**Comment by ntimo** [comment]
Habe keinen Anhang bekommen :( Auch in der E-Mail von Github ist keiner.

**Comment by lgund** [comment]
Dann hier nochmal:

Link: [https://teamspeak.first-coder.de/js.zip](https://teamspeak.first-coder.de/js.zip)

**Comment by ntimo** [comment]
Hi,
ja jetzt funktioniert es wie eine 1 :)

**Comment by lgund** [comment]
Alles klar ;)
