### ISSUE TITLE
Default Channel Nicht löschbar ?

### ISSUE THREAD

**Issue by ragman104** [First-Coder/TS3-Webinterface#21]
Entweder Bug oder ich hab ein verständnis Problem ^^

Bei einem über das Interface Frisch Instalierten Server kann man im Interface Nicht den Default Channel Löschen

Auch nicht wenn man schon einen weiteren Angelegt hat, auf dem TS server mit den SA unsw. geht es allerdings einwandfrei.

---
Fehlgeschlagen!
ErrorID: 775 | Message: invalid channel flags
---

Bug oder Feature ?

gruß
Mike

**Comment by lgund** [comment]
Der Fehler kommt direkt von der Teamspek Telnet Query. Ich würde nicht sagen, das es sich um ein Bug handelt. Man kann den Default Channel nicht löschen, da jeder Teamspeakserver einen Default Channel benötigt.

**Comment by ragman104** [comment]
Ok, ich bin nur von ausgegangen davon weil man den Default Channel ja auf dem TS direkt löschen kann sobald ein weitere vorhanden ist.

**Comment by lgund** [comment]
> Ok, ich bin nur von ausgegangen davon weil man den Default Channel ja auf dem TS direkt löschen kann sobald ein weitere vorhanden ist.

Kann ich nicht bestätigen:
![deault_channel](https://cloud.githubusercontent.com/assets/13957661/22300772/d2fcde08-e328-11e6-8453-4bd10b58d5b4.PNG)

**Comment by ragman104** [comment]
Hmmm Merkwürdig, hab ich eben auf einem gemacht. Ich schau mir das gleich noch einmal an. Melde mich wieder 

Danke, sry vorerst für Trouble

**Comment by lgund** [comment]
Das liegt vllt daran das du den standertserver flag raus hattest?
