### ISSUE TITLE
Teamspeakviewer Rework

### ISSUE THREAD

**Issue by lgund** [First-Coder/TS3-Webinterface#22]
Der Teamspeakserver ist leider immer noch ein wenig instabil. Ich werde ihn demnächst nochmals neu schreiben...

**Comment by lgund** [comment]
#finished and submitted in version 1.1.9

**Comment by lgund** [comment]
Looks like there are some Bugs... :/

**Comment by SoulofSorrow** [comment]
wenn ich joine den client kicke und wieder joine bleibt der gekickte client im serverviewer gelistet

![webinterface](https://cloud.githubusercontent.com/assets/20735208/22437674/2f718c70-e729-11e6-8800-b65326c509c9.JPG)

**Comment by lgund** [comment]
#fixed

Noch ein Fehler?
