### ISSUE TITLE
Icons Hochladen, Reload/Anzeige Problem?

### ISSUE THREAD

**Issue by ragman104** [First-Coder/TS3-Webinterface#23]
Folgendes.

Wenn ich bei einem Server ein Icon Hochlade tauch das Icon in der Liste der Hochgeladnen Icons erst auf wenn ich beim Server auf Zurück gehe(also in die server übersicht) dann wieder auf den server(mehr) und dann auch Icons.

Es würde ja reichen fürs erste wenn man schon in der server übersicht ist einfach den Icons Button nochmal drückt und er es dann reloaded, F5 drücken an der stelle ist wohl eher SubOptimal zumdem sich das Interface, macht man das an der stelle Tod lädt.

PS: test mit aktuellem Chrome/Win

Gruß
Mike

**Comment by lgund** [comment]
Muss ich schauen, da die icons eigentlich erst runtergeladen wird, wenn man auf server infos klickt. Ich schau mal ob ich das noch anders lösen kann ;)

**Comment by lgund** [comment]
#finished and submitted in version 1.1.9
