### ISSUE TITLE
Log Reader

### ISSUE THREAD

**Issue by ghost** [First-Coder/TS3-Webinterface#25]
Log Reader für Admins...
Admins sollen Logs auslesen können ("Webinterfacelogs")

**Comment by lgund** [comment]
Welche Admins denn genau?

**Comment by ghost** [comment]
Die Webinterface Admins :)

**Comment by lgund** [comment]
Du meinst ich sollte dafür ein neues Recht einführen

**Comment by ghost** [comment]
Ich mein die Logs die unter /logs/user.txt gespeichert werden

**Comment by lgund** [comment]
Ja aber die sollen doch über web erreichbar sein oder?

**Comment by ghost** [comment]
Ja

**Comment by lgund** [comment]
Also brauch doch diese Person Rechte. Sollten diese neue Rechte sein?

**Comment by ghost** [comment]
Jo neue rechte wie zb. User Logs einsehen usw...

**Comment by lgund** [comment]
Alles klar.... werde mal schauen ob sich da was einbringen lässt ;).

Irgendwie kommt mir dein Name bekannt vor, kennen wir uns irgendow her? Alpha?

**Comment by ghost** [comment]
Natürlich kennen wir uns xD Bin Mr. Cola der Typ der keine Zahlen lesen kann xD

**Comment by lgund** [comment]
So habe mir mal ein wenig Gedanken gemacht und die Logs angepasst. Im Anhang dazu ein Bild. Selbst suchen ist möglich ;).

![newlogs](https://cloud.githubusercontent.com/assets/13957661/22421971/4b385658-e6ea-11e6-8eed-e0e222101bd3.JPG)

**Comment by lgund** [comment]
Ich muss nurnoch das Recht hinzufügen :)

**Comment by lgund** [comment]
So in der neuen Version 1.2.9 gibt es nun auch ein globales Recht, was ermöglicht, in Server, sowie Benutzerlogs zu schauen.

**Comment by lgund** [comment]
Systemlogs sind je nach schwere auch in Farben unterteilt.
