### ISSUE TITLE
Channel Anlegen, permanent BUG ?

### ISSUE THREAD

**Issue by ragman104** [First-Coder/TS3-Webinterface#27]
Moin moin,

was mir eben so auffällt, kann es sein wenn ich einen Channel auf einem TS im Interface Anlege und troz Permanent Flag dieser nicht Permanent ist ?

Ich hab das jetzt eben mal auf einem Frischen TS versucht diesen runter gefahren und wieder Hoch, Der/Die Angelegten Channel sind nicht mehr da(troz Permanent).

Gruß
Mike

**Comment by ragman104** [comment]
Nachtrag,

ich konnte den fehler etwas Einschränken, es betrifft wohl nur den ERSTEN Server der mit einer Neuen Instanz erstellt wird. Also wenn man einen neuen TS Server erstellt und den dortigen Default Server Editiert.  Bei einem weiteren Server auf der Instanz Funktioniert das Permanente Channel erstellen.

Gruß
Mike

**Comment by lgund** [comment]
Kannst du mir mal step für step machen muss um den Fehler ebenfalls zu bekommen?

**Comment by ragman104** [comment]
Kein Ding.

Ich lege auf einem Server(linux in dem fall) einen Komplett NEUEN TS an sagen wir mit NonProfit Licens.

Dann nehme ich den laufenden Server und binde ihn wie gewohnt als Neue Instanz im Panel an, das Funktioniert auch alles soweit einwandrei.

In dem Fall Existiert auf dem Frischen server schon per default ein 32 Slot server der auch im Interface Sofort sichtbar ist und genau dieser hat das eingangs beschriebene Problem.

Wenn ich auf der Instanz Jetzt einen Neuen Server erstelle mit dem Interface, bei dem funktioniert alles einwandfrei. Nur wie gesagt der erste Server hat das Problem.

Ich habe das jetzt 3-4 mal versucht, ich kann es also Reproduzieren.

**Comment by trustsepp** [comment]
hallo!

Ich klinke mich mal dazwischen. 

Ich glaube, ich habe da den Fehler gefunden. 
Die Einstellung im WI:
Permanent = Semi-Permanent 
Semi-Permanent = Permanent

Ich hoffe ich konnte helfen (;

**Comment by ragman104** [comment]
das habe ich eben auch mal versucht auf dem "default server" also wenn ich es Tausche auf Semi Perm dann bleibt der channel auch erhalten nach einem Neustart, was nicht der fall ist wenn er auf Permanent erstellt wird.

Was komisch ist, bei weiteren erstellten Server scheint es zu passen.

**Comment by trustsepp** [comment]
ja, das ist allerdings mysteriös, das es bei anderen Servern funktioniert.

**Comment by lgund** [comment]
Ich werde es mir bei Gelegenheit anschauen ;). Momentan bin ich mit anderen Sachen noch beschäftigt :D

**Comment by lgund** [comment]
So habe nun die Channel erstellen Funktion der neuen Version 1.2.9 angepasst. Dabei ist mir auf gefallen dass....

> Permanent = Semi-Permanent
Semi-Permanent = Permanent

Kann ich bestätigen, wird in 1.2.9 behoben sein ;).
Des Weiteren funktioniert bei dem gleichen Selectmenu "Standardchannel" gar nicht. Wird aber in Version 1.2.9 behoben sein ;).
