### ISSUE TITLE
Version 1.2.9

### ISSUE THREAD

**Issue by lgund** [First-Coder/TS3-Webinterface#28]
Kompletter Remake des Interfaces:

- [x] Ordnerarchitektur neu angelegt
- [x] Hauptseite
- [x] Loginbereich
- [x] Server beantragen
- [x] Masterserver
- [x] Dashboard
- [x] Profil bearbeiten
- [x] Profilrechte
- [x] Admineinstellungen
- [x] Admin Instanzen
- [x] Benutzersteuerung
- [x] Maileinstellungen
- [x] Logs einsehen
- [x] Teamspeakserver
- [x] Server erstellen
- [x] Serveranträge
- [x] Tickets

Überarbeitungen:
- [x] main.js
- [x] admin.js
- [x] login.js
- [x] profile.js
- [x] teamspeak.js
- [x] ticket.js
- [x] Sprache Überarbeiten

Sonstige:
- [x] Installscript
- [x] SOAP Server / SOAP Client
- [x] Updater

**Comment by ghost** [comment]
Wenn ich bei was helfen kann, sag einfach Bescheid Igund.

**Comment by lgund** [comment]
Momentan wäre es gut wenn ich eine Testinstanz bekommen könnte. In dieser Testinstanz sollte es möglich sein min. 2 Server haben zu können. (Dauer ca. 2 Wochen)

**Comment by lgund** [comment]
done
