### ISSUE TITLE
Server Deteil Seite läd endlos mit php 7.1

### ISSUE THREAD

**Issue by ntimo** [First-Coder/TS3-Webinterface#3]
Hi,

Wenn ich versuche die Server deteil Seite aufzurufen, dann läd diese ewig. 
In der Serverlog steht das hier:
`AH01071: Got error 'PHP message: PHP Warning: Invalid argument supplied for foreach() in /var/www/vhosts/domain.com/domain.com/web_teamspeak_serverview.php on line 828\nPHP message: PHP Warning: Invalid argument supplied for foreach() in /var/www/vhosts/domain.com/domain.com/web_teamspeak_serverview.php on line 856\nPHP message: PHP Warning: Invalid argument supplied for foreach() in /var/www/vhosts/domain.com/domain.com/web_teamspeak_serverview.php on line 884\n', referer: https://domain.com/index.php?web_teamspeak_serverview?0?9`

Danke für die Hilfe :)

**Comment by ghost** [comment]
Mit **php 7.0.14** genau dasselbe. Habe erstmal auf **php 5.6** umgestellt damit es funtioniert.

**Comment by lgund** [comment]
Tritt der Fehler bei der Version 1.1.6 auf?

**Comment by ghost** [comment]
Mit der ver. 1.1.6-OPEN-BETA tritt es auf.

**Comment by lgund** [comment]
Hmm anscheinend gibt es keine Servergruppen? Ich habe es testweise mal angepasst.

LINK: [https://teamspeak.first-coder.de/fix.zip](https://teamspeak.first-coder.de/fix.zip)

Bitte einmal überschreiben und testen.

**Comment by ghost** [comment]
Nein leider nicht lädt und lädt

**Comment by SERVER-MSH** [comment]
`22187#0: *5425 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught Error: Call to undefined function split() in /var/www/vhosts/httpdocs/ts.server-msh.de/web_main.php:69
Stack trace:
#0 /var/www/vhosts/httpdocs/ts.server-msh.de/index.php(90): include()
#1 {main}
thrown in /var/www/vhosts/httpdocs/ts.server-msh.de/web_main.php on line 69" while reading response header from upstream`

**Comment by lgund** [comment]
> 22187#0: *5425 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught Error: Call to undefined function split() in /var/www/vhosts/httpdocs/ts.server-msh.de/web_main.php:69 Stack trace: #0 /var/www/vhosts/httpdocs/ts.server-msh.de/index.php(90): include() #1 {main} thrown in /var/www/vhosts/httpdocs/ts.server-msh.de/web_main.php on line 69" while reading response header from upstream

Dann hast du aber nicht die neuste version! Bitte schau nochmal.

Für:
> AH01071: Got error 'PHP message: PHP Warning: Invalid argument supplied for foreach() in /var/www/vhosts/domain.com/domain.com/web_teamspeak_serverview.php on line 828\nPHP message: PHP Warning: Invalid argument supplied for foreach() in /var/www/vhosts/domain.com/domain.com/web_teamspeak_serverview.php on line 856\nPHP message: PHP Warning: Invalid argument supplied for foreach() in /var/www/vhosts/domain.com/domain.com/web_teamspeak_serverview.php on line 884\n', referer: https://domain.com/index.php?web_teamspeak_serverview?0?9

Sollte dieser fix helfen: [https://teamspeak.first-coder.de/fix1.zip](https://teamspeak.first-coder.de/fix1.zip)

**Comment by ghost** [comment]
Von was die neueste Version?

**Comment by lgund** [comment]
1.1.6-open-beta vom webinterface ;)

**Comment by SERVER-MSH** [comment]
Diese Version habe ich die die es direkt bei euch zum Download gibt. ver. 1.1.6-OPEN-BETA

Jetzt der Fix brachte auch nichts. Läuft nicht auf php 7.0 und 7.1

**Comment by SERVER-MSH** [comment]
Jetzt geht es. Super
Habe aber noch eine Fehlermeldung was kann das sein?

`28891#0: *92 FastCGI sent in stderr: "PHP message: PHP Warning: filesize(): stat failed for logs/user in /var/www/vhosts/server-msh.de/httpdocs/functions.php on line 121
PHP message: PHP Warning: filesize(): stat failed for logs/user.zip in /var/www/vhosts/httpdocs/functions.php on line 145" while reading response header from upstream`

**Comment by SERVER-MSH** [comment]
`28891#0: *92 FastCGI sent in stderr: "PHP message: PHP Warning: Invalid argument supplied for foreach() in /var/www/vhosts/httpdocs/ts.server-msh.de/web_teamspeak_serverview.php on line 828
PHP message: PHP Warning: Invalid argument supplied for foreach() in /var/www/vhosts/server-msh.de/httpdocs/web_teamspeak_serverview.php on line 856
PHP message: PHP Warning: Invalid argument supplied for foreach() in /var/www/vhosts/server-msh.de/httpdocs/web_teamspeak_serverview.php on line 884" while reading upstream`

**Comment by ntimo** [comment]
Jetzt geht es wie eine 1, seit dem Upadte :) Danke

**Comment by ghost** [comment]
Jup bei mir auch. Vielen Dank

**Comment by lgund** [comment]
Das freut mich, also scheint mit der Version 1.1.7-OPEN-BETA PHP-7 unterstützt zu werden! :)
