### ISSUE TITLE
Aktuelle PHP Version 7.1.2

### ISSUE THREAD

**Issue by ghost** [First-Coder/TS3-Webinterface#32]
Mit der aktuellen PHP Version nicht lauffähig.

Fehler:

`11644#0: *2370 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught Exception: Could not gather sufficient random data in /var/www/vhosts/httpdocs/functions.php:30
Stack trace:
#0 /var/www/vhosts/httpdocs/functions.php(30): session_start()
#1 /var/www/vhosts/httpdocs/index.php(25): require_once('/var/www/vhosts...')`

**Comment by lgund** [comment]
Besteht der Fehler immernoch?

**Comment by trustsepp** [comment]
Also auf meinem Server läuft ebenfalls PHP 7-1-2 - und das WI zeigt keine Fehler.

**Comment by lgund** [comment]
Alles klar. PHP 7 ist ja immer noch eine relativ neue Version und daher kann es immer wieder zu temporären Problemen führen. Falls wieder ein Problem auftaucht einfach diesen topic wieder öffnen.

**Comment by ghost** [comment]
Also bei mir gehts nicht. PHP 7.1.2 mit nginx.

`11644#0: *2370 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught Exception: Could not gather sufficient random data in /var/www/vhosts/httpdocs/functions.php:30 Stack trace: #0 /var/www/vhosts/httpdocs/functions.php(30): session_start() #1 /var/www/vhosts/httpdocs/index.php(25): require_once('/var/www/vhosts...')`

**Comment by lgund** [comment]
Komisch... Aber session_start() exisitiert in php 7....

**Comment by ghost** [comment]
Kann geschlossen werden. Mit dem Update heut auf die PHP Version 7.1.3 funktioniert es ohne Probleme.

**Comment by lgund** [comment]
Falls trotzdem noch Probleme auftauchen, bin ich jederzeit hier ;).

**Comment by ghost** [comment]
Weiss ich doch Igund.
