### ISSUE TITLE
teamspeakCommands.sh bekommt nicht genug Rechte

### ISSUE THREAD

**Issue by Nevsix** [First-Coder/TS3-Webinterface#33]
Bei mir bekommt die teamspeakCommands.sh nicht genug Rechte obwohl ich allen Ordnern Vollzugriff gegeben hab.
![screenshot_7](https://cloud.githubusercontent.com/assets/1899372/24304476/c877c588-10b9-11e7-8dc5-129baa1bdf1a.png)

LG 
Keksi1996

**Comment by lgund** [comment]
Ja momentan gibt es da ein Bug bei Windows. Bitte gehe mal in die check_database.php.

In ca. Zeile 70 wirst du die Zeile finden wo du einfach das Recht von 0777 auf 0666 ändern kannst. Du könntest auch die komplette Rechteabfrage da einfach entfernen. Die ist in der neuen Version eh besser geregelt :D

**Comment by lgund** [comment]
konntest du denn Fehler beheben?
