### ISSUE TITLE
Instanz Shell

### ISSUE THREAD

**Issue by ghost** [First-Coder/TS3-Webinterface#34]
Hallo zusammen,

bekomme es nicht zum laufen. Folgendes wird aus gegeben.

`################################################################# Welcome to the Teamspeak Commandsscript from First-Coder @autor L.Gmann ################################################################# ################################################################# ERROR ! Private key not found. Upload the Private key under shell/teamspeak3 ################################################################# `

Private Key wurde erstellt. Vielleicht habe ich da auch was falsch gemacht. Gibt es ein Tutorial wie genau sowas funktioniert?

**Comment by lgund** [comment]
Der sucht den Key als Benutzername im Ordner shell/. In deinem Fall also shell/teamspeak3. Allerdings wird dies in der neuen Version teilweise abgeschafft. Werde das Shell script mit php shell ablösen.
