### ISSUE TITLE
Mail-Einstellungen

### ISSUE THREAD

**Issue by Provokan** [First-Coder/TS3-Webinterface#35]
Hallo, 

erst einmal vielen dank für die veröffentlichen deines Panels, 
dies hat mir viel Arbeit abgenommen. 

Jedoch möchte ich Sie bitten alle emails zu erlauben, viele meiner Freunde benutzen keine web.de oder gmail.com domain sondern privatisierte wie @provo.ovh o.Ä.

oder wie kann ich diese einstellungen deaktivieren?

**Comment by lgund** [comment]
Eigentlich sollte es keine Einschränkung jeglicher Mails geben, da diese über ein Regex erfasst werden. Der Regex für mail lautet wie folgt:

> /^[-a-z0-9~!$%^&*_=+}{\'?]+(\.[-a-z0-9~!$%^&*_=+}{\'?]+)*@([a-z0-9_][-a-z0-9_]*(\.[-a-z0-9_]+)*\.(aero|arpa|biz|com|coop|edu|gov|info|int|mil|museum|name|net|org|pro|travel|mobi|[a-z][a-z])|([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}))(:[0-9]{1,5})?$/i

Welche Endung hat den diese Mailaddresse?

**Comment by Provokan** [comment]
Hallo,

ich kann mich z.N mit Provo.ovh unter wi.provo.ovh nicht registrieren.
das geht bei @becker.de auch nicht

**Comment by lgund** [comment]
> das geht bei @becker.de auch nicht

Das kann ich nicht bestätigen. Bei mir geht z.B. test@becker.de

> Provo.ovh

Probiere mal folgenden Regex:

/^[-a-z0-9~!$%^&_=+}{'?]+(.[-a-z0-9~!$%^&=+}{'?]+)*@([a-z0-9][-a-z0-9_](.[-a-z0-9_]+).(ovh|aero|arpa|biz|com|coop|edu|gov|info|int|mil|museum|name|net|org|pro|travel|mobi|[a-z][a-z])|([0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}))(:[0-9]{1,5})?$/i

**Comment by Provokan** [comment]
Danke erst einmal für die schnelle hilfe, aber in welcher datei soll ich den regex abändern?

**Comment by lgund** [comment]
Schaue mal unter /js/webinterface/. Die Regex wird mehrmals verwendet und ich habe dafür keine eindeutige definition, sondern jedesmal den regex eingefügt. Vllt. sollte ich das mal "globalisieren" :)

**Comment by lgund** [comment]
Hat es funktioniert?

**Comment by Provokan** [comment]
Ja hat funktioniert (:
