### ISSUE TITLE
iframeServerView.php fehlt

### ISSUE THREAD

**Issue by ghost** [First-Coder/TS3-Webinterface#37]
Hallo Igund,

im Ordner php fehlt die iframeServerView.php. Zumindest ist sie bei mir nicht vrohanden. Hab es mal direkt runter geladen aber dort ist sie auch nicht enthalten.

**Comment by lgund** [comment]
Du benutzt den Viewer? Also der Viewer ist vorhanden :)

**Comment by lgund** [comment]
Ich habe soeben mal eine nochmal ein leicht geändertes packet runtergeladen, da im interface der link falsch angegeben wurde. Dort wurde /php/iframe..php angegeben es muss aber /iframe...php sein!

**Comment by ghost** [comment]
Wo ändere ich das?

**Comment by lgund** [comment]
Ich habe es in den hochgeladenen dateien schon geändert.

Wenn du es selber machen willst:

1. Gehe unter /php/teamspeak/web_teamspeak_serverview.php
2. Sucher dort nach "iframe"
3. Lösche das /php/

**Comment by ghost** [comment]
> Ich habe es in den hochgeladenen dateien schon geändert.

Okay danke. Kommt noch keine Meldung das es ein Update gibt. Deswegen ändere ich es nach deinen Anweisungen.

**Comment by lgund** [comment]
Ja habe es noch schnell in der aktuellen beigelegt. Ich wollte noch ein wenig auf eine neue Version warten.

Hat es denn funktioniert?

**Comment by ghost** [comment]
Ja hat bestens funktioniert nun läuft erstmal alles.

**Comment by lgund** [comment]
Perfect!
