### ISSUE TITLE
Token werden nicht erstellt

### ISSUE THREAD

**Issue by ghost** [First-Coder/TS3-Webinterface#38]
Hi Igund,

es werden keine Token erstellt. Bei mir zumindest kommt nach absenden

```
Fehlgeschlagen!
undefined
```

**Comment by lgund** [comment]
Nur Channeltoken richtig?

**Comment by lgund** [comment]
Ok habe den Bug gefunden und die korrigierte Version hochgeladen!

Und zwar wird immer ein Token weniger erstellt. Sprich aus 2 Token wird 1 und eben aus 1 token wird undefined (keiner).

Um den Fehler selbst zu beheben macht man folgendes:

1. Gehe unter /php/functions/functionsTeamspeak.php
2. Gehe in Zeile 678
3. Ändere `for($i = 1; $i < $number; $i++)` zu `for($i = 0; $i < $number; $i++)`

**Comment by ghost** [comment]
Danke hab ich geändert nun geht es. Ging für den Serveradmin nicht, die Channeltoken hatte er erstellt.

**Comment by lgund** [comment]
> die Channeltoken hatte er erstellt.

kam darauf an, wie viele Tokens du erstellt hast. Musste eben größer 1 sein.

PS vielen Dank das du den Bot so durchcheckst 👍

**Comment by ghost** [comment]
Nix zu danken. Schließlich soll es ja mal irgendwann aus der Beta raus.
