### ISSUE TITLE
Teamspeak Interface Querybot

### ISSUE THREAD

**Issue by lgund** [First-Coder/TS3-Webinterface#39]
Add the query bot into the interface:

- [ ] Multiinstance
- [x] Connecting to the database
- [x] AFK Mover
- [x] Idle AFK Sgroup
- [x] Switch if muted Mic / Headset
- [x] Bad Names
- [x] Bad Channels
- [x] Connecting / Disconnecting Info
- [x] Advertising Text
- [x] Servergroup Protection
- [ ] Sticky Channel
- [x] Forbidden record
- [ ] Sgroup Notifications
- [ ] Inactive Clientcleaner
- [x] ~Special Welcomemessage (With specific sgroup)~ Welcome Message with immun Servergroup
- [ ] Automatic reconnect, if disconnect

Wish me Luck guys 👍

**Comment by ghost** [comment]
Mal kurz gefragt wird es solch ein Bot werden wie hier angeboten wird? https://www.stefan1200.de/forum/index.php

Nur komplett ins TS Webinterface integriert?

**Comment by lgund** [comment]
Es war eigentlich geplant den JT3 Bot von stefan1200 ins interface zu integrieren, allerdings hatte ich mit ihm eine weniger schöne Auseinandersetzung. Schluss endlich kam ich zu dem Schluss seine illegalen Machenschaften nicht zu unterstützen, um sein verschlüsselten Bot zu nutzen. Den dieser müsste vorher gekauft werden und ist dann trotzdem nicht gewerblich nutzbar.

Jedenfalls werde ich, falls version 2 erscheint, genau den selben bot in open source unter gnu gplv3 nachbauen. Dieser wird allerdings auf keinen fall in java sein, sondern in einer anderen Sprache, auf die ich später eingehen werde.

Mehr infos zu diesem Thema gibt es auch noch hier: https://scriptzbase.org/threads/alpha-teamspeak-3-webinterface.52726/page-9

**Comment by ghost** [comment]
> Schluss endlich kam ich zu dem Schluss seine illegalen Machenschaften nicht zu unterstützen, um sein verschlüsselten Bot zu nutzen.

Ah okay. Würdest du mir das mal näher per Email erklären? @lgund 
Meine Daten findest ja in meinem Profil. https://github.com/SERVER-MSH

**Comment by lgund** [comment]
Will be forwarded to [https://github.com/First-Coder/TS3-Control](https://github.com/First-Coder/TS3-Control)
