### ISSUE TITLE
Interface gebannt, trotz whitelist Eintrag

### ISSUE THREAD

**Issue by lgund** [First-Coder/TS3-Webinterface#4]
Das interface flooded den Teamspeakserver zu stark. Fix ist in der mache ;)

**Comment by ghost** [comment]
Hast Du eine kurze Erklärung dafür?

> Das interface flooded den Teamspeakserver zu stark.

**Comment by lgund** [comment]
Aus irgendeinem Grund werden zu viele Abfragen vom Interface gestartet. Um dies momentan zu beheben muss die flood Grenze von 10 auf 100 angehoben werden. Ein fix dafür ist in Arbeit, wird aber noch eine Weile dauern.

**Comment by ghost** [comment]
Ah okay

**Comment by lgund** [comment]
Sollte in der neuen Version behoben sein :D
