### ISSUE TITLE
Änderungen nur an den php Dateien?

### ISSUE THREAD

**Issue by ghost** [First-Coder/TS3-Webinterface#40]
Hi Igund,

sehe ich das gerade richtig das man an diesen beiden php Dateien nur manuelle Änderungen vornehmen kann?

`custom_dashboard.php` `custom_news.php`

Gibt es da nicht vielleicht die Möglichkeit das vom Interface aus zu machen? Gefunden habe ich diesbezüglich nichts.
Und wenn das nicht Möglich sein sollte, dann sollte man es so überarbeiten damit Umlaute auch richtig dargestellt werden, was ja im Moment nicht so ist. Aus ä,ü,ö sind kyrillische Zeichen man muss erst sowas `f&#252;` einsetzen damit es richtig dargestellt wird.

**Comment by lgund** [comment]
> Gibt es da nicht vielleicht die Möglichkeit das vom Interface aus zu machen? 

Inwiefern? Es ist eigentlich dafür gedacht um solche MOTD Sachen zu machen oder andere Seiten zu laden mithilfe mit php header.

Ich werde mal schauen, ob ich das mit den Umlauten hinbekomme 👍

**Comment by lgund** [comment]
Bitte schaue mal hier:

> https://demo.first-coder.de/entwicklung/NEW/index.php?web_main_main

Habe jetzt einfach mal umlaute reingeschrieben, die ohne Probleme angezeigt werden. Was zeigt denn deine Seite?

**Comment by ghost** [comment]
@lgund so sieht es bei mir aus mit dem ü zum Beispiel.

Der Hafen f�r Gestrandeten im Server-Universum die Hilfe suchen. F�r die, die etwas zu sagen haben, f�r Entwickler, einfach f�r alle.

**Comment by lgund** [comment]
Die Datei muss mit UTF-8 ohne DOM konvertiert sein. Vllt. hast du diese ja ausversehen geändert. Falls du den Notepad++ verwendest, so schaue unter dem Reiter "Kodierung"

**Comment by ghost** [comment]
@lgund ja habs eben mitbekommen. Ich arbeite mit UltraEdit habe es dort für php eingestellt nun läuft es bestens. Danke dir.
