### ISSUE TITLE
Upgradeverlauf

### ISSUE THREAD

**Issue by ghost** [First-Coder/TS3-Webinterface#41]
@lgund hier mal ein großes Lob an dich und dein Interface. Es läuft perfekt habe zumindest bis jetzt keine weiteren Fehler gefunden. Die die ich gefunden habe sind ja schon wieder abgearbeitet worden und erledigt.
Das Upgrade von der 1.1.8 auf die jetzige neuste Version verlief auch tadellos. So bleibt wirklich nur zu hoffen das das Projekt bestehen bleibt und sich nicht im Sande verliert wie viele eigentlich viel versprechende Projekte. Ich bin immer wieder gern dabei soweit es mir möglich ist dich weiter zu Unterstützen.

**Comment by lgund** [comment]
Das freut mich zu hören. Ich hoffe selbst, dass das Interface irgendwann mal so bekannt wie manch andere (z.B. psychokillers wird)

**Comment by ghost** [comment]
Das wird es. Ich sorge dafür mit und mache gut Werbung.
