### ISSUE TITLE
Remove all Warnings

### ISSUE THREAD

**Issue by lgund** [First-Coder/TS3-Webinterface#43]
I need to get and remove all warnings in the interface. If you found some, please send me the log file or post here the warnings. Thanks :)

**Comment by DJDosKiller** [comment]
```
2017-06-27 21:55:21	|		ERROR		|	getKeys (SQL Error):No database selected
2017-06-27 21:55:51	|		ERROR		|	getKeys (SQL Error):No database selected
2017-06-27 21:55:55	|		ERROR		|	getKeys (SQL Error):No database selected
2017-06-27 21:55:57	|		ERROR		|	getKeys (SQL Error):No database selected
```
erscheint jedesmal in der log wenn ich installieren drücke.
außerdem sind folgende fehler auf der seite zu sehen:
```
Warning: fwrite() expects parameter 1 to be resource, boolean given in C:\xampp\htdocs\php\functions\functions.php on line 346

Warning: filesize(): stat failed for ../../logs/system.log in C:\xampp\htdocs\php\functions\functions.php on line 347
```

kann das webinterface nicht installieren weil nichts passiert und nur die aufgeführten error meldungen in der log erscheinen.
Letztere fehler sind direkt beim aufrufen der seite zu sehen.

**Comment by lgund** [comment]
Danke vorerst für die Warnungen. Werde sie im nächsten update beheben. Es wäre gut wenn du mir später weitere warnungen zukommen lassen kannst.

Nun zu deinem problem. Das anzeigen der Fehlermeldung auf der seite verfälscht die Antwort der ajax requests. Um das zu beheben musst du abstellen, dass die warnungen auf der homepage erscheinen. Du musst also in die php.ini gehen und display_errors auf off stellen und im Anschluss den webserver neu starten. Damit werden warnungen und fehler in der log gespeichert, aber nicht auf der homepage gezeigt.

Bitte gebe mir bescheid falls es funktioniert bzw. Nicht funktioniert hat.

**Comment by DJDosKiller** [comment]
ja. jetzt funktioniert es. danke 👍

**Comment by lgund** [comment]
```
2017-06-27 21:55:21	|		ERROR		|	getKeys (SQL Error):No database selected
2017-06-27 21:55:51	|		ERROR		|	getKeys (SQL Error):No database selected
2017-06-27 21:55:55	|		ERROR		|	getKeys (SQL Error):No database selected
2017-06-27 21:55:57	|		ERROR		|	getKeys (SQL Error):No database selected

Warning: fwrite() expects parameter 1 to be resource, boolean given in C:\xampp\htdocs\php\functions\functions.php on line 346

Warning: filesize(): stat failed for ../../logs/system.log in C:\xampp\htdocs\php\functions\functions.php on line 347
```

fixed in 1.3.10
