### ISSUE TITLE
Keine Verbindung mit TS3 Server möglich

### ISSUE THREAD

**Issue by Jniklas2** [First-Coder/TS3-Webinterface#44]
In der neuen Version (1.2.9-OPEN-BETA) kann ich zwar die Instanz ohne Probleme hinzufügen aber wenn ich übers Dashboard mir die Server anzeigen lassen möchte steht da immer das der Bot gebannt wäre aber er geht über den serveradmin Account rein und die IP ist auch schon auf der Whitelist. Und die Flood Grenze steht gerade sogar auf 50000. Hab schon mehrere male das gesamte Webinterface neuinstalliert (inklusive neu Erstellung der MySQL Datenbanken), hat aber auch kein einziges Mal geholfen. Das Passwort vom serveradmin Account hatte ich auch schon mal auf nur 11 Kleinbuchstaben geändert ohne das es geholfen hat. Die vorherige Version hatte ohne Probleme funktioniert.

Hoffe jemand kann mir helfen

MfG  Jniklas2

P.S: In den logs steht auch nichts darüber drin

**Comment by lgund** [comment]
Wurde schon mal probiert, wenn es "angeblich" gebannt wurde per server über telnet einfach mal zuzugreifen?

**Comment by caneabi** [comment]
Hier genau dasselbe

**Comment by Jniklas2** [comment]
Ich kann mich über meinen PC und über den Server mit Telnet auf den TS3 Server verbinden

**Comment by Jniklas2** [comment]
Aber jetzt gerade zeigt mir das Webinterface das hier an: 
 ErrorID: 520 | Message: invalid loginname or password

**Comment by caneabi** [comment]
Ist ein Fehler im Framework habe ich bei mehreren Bots

**Comment by caneabi** [comment]
Ja weil der warum auch immer denkt das pw ist falsch und wird dann wegen zu vielen Fehlversuchen gebannt aber das Passwort ist richtig

**Comment by Jniklas2** [comment]
Kann man das irgendwie beheben?

**Comment by caneabi** [comment]
Ich hab bisher​ keine Lösung gefunden :/

**Comment by Jniklas2** [comment]
schade :/

**Comment by lgund** [comment]
bitte kommt dafür mal ins Teamspeak... first-coder.de:4244. Ich bin noch ca. 40min da

**Comment by Jniklas2** [comment]
bin da

**Comment by caneabi** [comment]
Ok komme dann

**Comment by lgund** [comment]
Bug wurde gefunden und aufgenommen. Falls bei jemanden anderen der gleiche Fehler vorliegt, so geht sicher, dass unter config/instance.php das richtige Serveradmin Passwort hinterlegt ist! Das Webinterface macht in der Version 1.2.9 ein Übertragungsfehler!
