### ISSUE TITLE
Portangaben bei Serverbeantragung.

### ISSUE THREAD

**Issue by Provokan** [First-Coder/TS3-Webinterface#46]
Guten Morgen, 

Ist es möglich das man eine Port Ranche angeben kann und die belegten dann auch ausgegraut werden, so das sieht welcher Port aufwärts frei ist ? 

Denke dies wäre ein cooles Feature

**Comment by lgund** [comment]
Wie genau stellst du dir das vor? Gibt der Benutzer den Portpool vor?

**Comment by Provokan** [comment]
Jaein, das wenn jemand ein Serverantrag stellt, sieht welche Ports schon belegt sind,  so dass jemand nicht ein Antrag mit dem Port 9987 stellt. 

Oder man gibt in der Globalen Einstellungen 5 Ports ein, wo man sich dann einen bei deinem Eintrag aussuchen kann

**Comment by lgund** [comment]
Meinst du das wird wirklich noch benötigt?

**Comment by Provokan** [comment]
Für Provider wäre es sinnvoll bzw wenn man ein Teamspeak sponsoring betreibt, dass eine gewisse Port Range hat, da man dies auch in der Firewall ordentlich einbinden kann. Ich bin z.b kein Freund von willkürlichen Ports wie z.b 1337 oder 16795

Bei mir sind die Ports wie folgt frei 9987  - 9997

**Comment by lgund** [comment]
Hmm momentan ist es zumindest so geplant, dass man eine Instanz und eine Anzahl an Server angibt um das sponsoring oder hosting anzuzeigen. Somit ist sogar zu sehen wie viel Server noch verfügbar sind. Zudem wird der Rest dann in einer warzeschleife angezeigt. Eine portrange könnte ich zudem auch noch einsetzen. Das wäre vllt. Interessant.
