### ISSUE TITLE
Html encoding Bug

### ISSUE THREAD

**Issue by caneabi** [First-Coder/TS3-Webinterface#47]
Hey , wenn man Leute im TS Poked oder Nachrichten schreibt dann wird das noch in html ausgegeben sprich für Leerzeichen werden zb 20% eingefügt usw...

**Comment by lgund** [comment]
Hallo,
bitte versuche mal folgendes und gebe mir bescheid, ob das den Fehler behebt:

1. Öffne php/functions/functionsTeamspeakPost.php
2. Suche nach "TeamspeakServerClientAction"

Das Suchergebnis sollte dich zu einer Zeile führen, die ungefähr so aussieht:
> echo TeamspeakServerClientAction($_POST['action'], $_POST['message'], $_POST['clid'], (isSet($_POST['cid'])) ? $_POST['cid'] : '', $_POST['port'], $_POST['instanz'], (isSet($_POST['kickmode'])) ? $_POST['kickmode'] : '');

3. Ändere "$_POST['message']" zu "urldecode($_POST['message'])"
4. Fertig ;)

**Comment by caneabi** [comment]
Werde es dann mal testen ;)

**Comment by caneabi** [comment]
Ok funktioniert nun, würde es vielleicht ins nächste updaten mit einbauen ;)

-Geschlossen

**Comment by lgund** [comment]
Es ist selbstverständlich im nächsten update behoben
