### ISSUE TITLE
Automatische Freischaltung im Webinterface 

### ISSUE THREAD

**Issue by Provokan** [First-Coder/TS3-Webinterface#48]
Guten Abend, 

Mir ist noch etwas eingefallen, aktuell ist es so, wenn jemand ein Server beantragt und man diesen Freischaltet, fehlen dem "Besitzer/Admin" immer noch die Permission sich im Panel einzuloggen, ist es eventuell möglich dies mit der Freischaltung des Servers zu automatisieren so dass er auch auf seine Server Einstellungen zugreifen kann ?

**Comment by lgund** [comment]
Sicher das der Benutzer im geblockten Zustand erstellt wird ?

**Comment by Provokan** [comment]
Ich habe es bei mir getestet indem ich ein Server beantragt hatte und der Nutzer des beantragten Servers hatte nach der Freigabe keine Berechtigung sich auf der Website einzuloggen

**Comment by lgund** [comment]
Ich werde mal schauen ob ich da ein bug finde, brauchst du dann ein schnellen fix oder reicht das, wenn du bis zur 1.3.10 wartest?

**Comment by Provokan** [comment]
Quatsch, es reicht vollkommen mit den nächsten Updates.

**Comment by lgund** [comment]
So habe es gerade mal getestet. Konnte es nicht erreichen, dass der Benutzer, nachdem er durch den Serverantrag erstellt wurde, gesperrt ist. Er besitzt Einlogrechte, sowie alle Rechte zum Server (außer Server bearbeiten).

**Comment by Provokan** [comment]
Sobald der Nutzer erstellt ist, befindet sich jedoch der Reiter weiterhin auf nein, hier ein Screenshot von dem Benutzer

http://imgur.com/a/Fswqj

desweiteren ist mir ein Schreibfehler aufgefallen, Geschrieben wurde Standertgruppe anstatt Standartgruppe 

http://imgur.com/a/bfbrT

**Comment by lgund** [comment]
Ach verdammt.... Ich dachte der Nutzer wäre geblockt :/ Ja alles klar wird im nächsten Update gefixt werden!

> desweiteren ist mir ein Schreibfehler aufgefallen, Geschrieben wurde Standertgruppe anstatt Standartgruppe

Werde ich ebenfalls fixen 👍. In der neuen Version wird ebenfalls Italienisch hinzukommen

**Comment by lgund** [comment]
fixed in version 1.3.10 and upper
