### ISSUE TITLE
Teamspeak Viewer Spacer

### ISSUE THREAD

**Issue by BloodDragon2580** [First-Coder/TS3-Webinterface#49]
Ich habe keine Ahnung deswegen frage ich einfach mal drauf los^^
Ist es möglich bei den Channel name z.B. "**[spacer 27]【●▪> ƬƛԼƘ 2**" das "**[spacer 27]**" ausblenden zu lassen.
Und den Background Transparent zu machen?. Der grüne Hintergrund sieht zwar schick aus passt aber nicht zur Homepage^^.

**Comment by lgund** [comment]
Du meinst, wenn man auf einem Channel klickt, dass das [spacer 27] wegfällt? Oder hast du das im Viewer selbst?

**Comment by BloodDragon2580** [comment]
Im Viewer selbst. Hatte mal irgendwo nen viewer wo das unsichtbar war deswegen frage ich.
![ts](https://user-images.githubusercontent.com/1429236/27013637-b013b562-4ee7-11e7-8313-bebfe56abbf8.jpg)

**Comment by lgund** [comment]
Das ist dann wohl eher ein Bug. Mich wundert es bloß ein wenig, denn wie du siehst werden die ersten cspacer nicht gezeigt. Wie sieht es denn im Teamspeak selbst aus. Steht dort auch cspacer oder nicht?

PS ich glaube ich habe den Fehler schon gefunden. Bitte entferne mal das leerzeichen. Sprich mach aus:

> [cspacer 04] Mein Channelname

zu

> [cspacer04] Mein Channelname

Ich glaube dann wird es funktionieren.

**Comment by BloodDragon2580** [comment]
Jo das wars^^ Die sind mir gar nicht aufgefallen. Ich bedanke mich vielmals^^. Gibts auch ne möglichkeit den hintergrund Transparent zu machen?

**Comment by lgund** [comment]
Nein momentan ist eine solche Einstellung nicht vorgesehen. Allerdings bleibt einem immer noch die manuelle Anpassung. Wenn du mal in die iframeServerView.php schaust findest du diesen Codeteil:

		`<style>
			.tree-background-success
			{
				background-color: rgba(0, 199, 0, 0.2);
				border: 1px solid rgba(0,255,0,0.4);
				border-radius: 4px;
			}
			
			.tree-background-failed
			{
				background-color: rgba(199, 0, 0, 0.2);
				border: 1px solid rgba(255,0,0,0.4);
				border-radius: 4px;
			}
		</style>`

Wenn du hier background-color einfach auf transparent setzt, sollte das dein Problem lösen :+1: 

PS natürlich müsste auch der border auf 0px gestellt werden

**Comment by BloodDragon2580** [comment]
thx chefe
