### ISSUE TITLE
Backups sind nicht durch .htaccess gesichert

### ISSUE THREAD

**Issue by ntimo** [First-Coder/TS3-Webinterface#5]
Hi,
die Backups können einfach so per Url aufgerufen werden, vielleicht sollten diese lieber per .htaccess geschützt werden. So das diese niemand downloaden kann, da diese ja auch senible daten enthalten.

Danke,
Timo

**Comment by lgund** [comment]
Da müste ich mal genauer schauen wie ich das mache... Man will sie ja auch runterladen können. Ist natürlich verständlich, dass ein fremder kein Zugang drauf haben sollte.

**Comment by ntimo** [comment]
Vlt mit einem Token ;) Der vom Skript bei der Installation random generiert wird.

```
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteCond %{QUERY_STRING} !key=somerandomtokenhere
RewriteRule (.*) - [F]
</IfModule>
```

**Comment by lgund** [comment]
Ich komme die Tage mal im ts... dann schauen wir zusammen mal ;)

**Comment by ntimo** [comment]
Klar, sag mir nur bescheid wann und auf welchem TS3 Server ;)

**Comment by lgund** [comment]
Ich komme einfach mal in deinem ;)

**Comment by lgund** [comment]
Habe es nun leichter hinbekommen ;). Mein Lösung:

> function downloadBackup($kind, $name)
{
	$dir			=	"";
	switch($kind)
	{
		case 'channel':
			$dir	=	"backup/channel/";
			break;
		case 'server':
			$dir	=	"backup/server/";
			break;
	};
	header("Content-Type: application/json");
	header("Content-Disposition: attachment; filename=\"$name\"");
	return readfile($dir.$name);
};

Wird im nächsten Backup installiert sein (1.1.10-OPEN-BETA)
