### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by caneabi** [First-Coder/TS3-Webinterface#50]
Hey gibt es eine möglichkeit im viewer einzustellen das die clients und Gruppen nach talkpower sortiert werden? Denn hier ist es nicht der fall (https://hardcoregamers.de/viewer)
Wenn ja wie?

**Comment by lgund** [comment]
Es ist möglich, allerdings momentan nicht eingebaut. Wie wichtig ist es dir denn?

**Comment by caneabi** [comment]
Es geht schon würde mir reichen wenn du mir sagst was ich machen muss .

**Comment by lgund** [comment]
Es wäre wichtig zu wissen ob du den live viewer verwenden willst oder nicht

**Comment by caneabi** [comment]
Ich möchte den Live viewer schon verwenden

**Comment by lgund** [comment]
Ich versuche es morgen mal :)

**Comment by lgund** [comment]
Also das wird wohl doch etwas länger dauern als erwartet... Ich hoffe es hat keine Eile :/

**Comment by caneabi** [comment]
Nene mach dir kein Stress ;)

**Comment by lgund** [comment]
Dieses Feature wird für die Webinterface Versionen nicht mehr kommen. Eine alternative könnte hier der spätere Teamspeak Control sein, da dieser im Viewer weitaus mehr dynamisch ist.
