### ISSUE TITLE
Formatierungsfehler beim Senden von Nachrichten

### ISSUE THREAD

**Issue by remixjunky** [First-Coder/TS3-Webinterface#51]
Einen User über die "Serverübersicht" anzuschreiben mit mehreren Leerzeichen dazwischen wird immer mit einem "%20" statt einem Leerzeichen getrennt!

"<16:14:56> "serveradmin from 127.0.0.1:57384" schloss sich dem Chat wieder an.
<16:14:56> "Hostinterface": Test%20finde%20ich%20toll
<16:14:56> Ihr Chat Partner hat seine Verbindung getrennt."

**Comment by lgund** [comment]
Danke für den Bugreport. Allerdings ist dieser schon bekannt und wird in der nächsten Version gefixt. Falls du es vorher schon mal beheben willst, schaue hier bei #47 .
