### ISSUE TITLE
Server Gruppen Rechte einstellen

### ISSUE THREAD

**Issue by Provokan** [First-Coder/TS3-Webinterface#52]
Guten Morgen,

ich habe eine Frage ist es geplant das man in Zukunft auch über das Webinterface Server Gruppen erstellen kann oder vorhandenen Gruppen bearbeiten kann?

**Comment by lgund** [comment]
Also geplant ist es nicht, da ich nicht weiß ob es sinn macht. Wozu bräuchte man sowas?

**Comment by Provokan** [comment]
In erster Linie denke ich wird dies als vollständige alternative für das Psychokillers Webinterface agieren können und zur meinem zwecken, ich möchte bzw habe aktuell auf meinem Server keine Server gruppe der ich erlaub habe an den Gruppen etwas zu verändern, da ich dies immer fürs Psychokillers gemacht habe um zu verhindern das niemand einfach mal etwas an der Gruppe verändern

**Comment by lgund** [comment]
Hättest du eine Idee, wie du das Menu umsetzen würdest, sodass es immer noch responsive ist?

**Comment by Provokan** [comment]
Das Menu würde ich wie folgt vorstellen.

Es werden alle Permissions gelistet und rechts am Rand dann eventuell ein Schraubenschlüssel, 
wenn man diesen öffnet dass sich in einem hover (popup) dann die einzustellenden Werte erscheinen. 

dies wäre auch Smartphone tauglich

**Comment by lgund** [comment]
Channel-, Server- und Clientrechtebäume werden in der Version 2 mit integriert. In der Version 1 ist der Platz nicht ausreichend genug. Da wird das ganze zu unübersichtlich

**Comment by mumi** [comment]
Wie weit ist dieses Vorhaben fertig? Screenshots? Dieses feature ist der einzige Grund warum neben ich nebenbei noch Psychokillers Webinterface habe.

**Comment by lgund** [comment]
Dieses feature ist mittlerweile ein festes Bestandteil von v2. Es ist vis jetzt in der grundversion 2.0.0 nicht eingebettet, wird allerdings in nächster Zeit nachgetragen.

Ich muss allerdings vorerst meine Semester Prüfungen bestehen :)

Geplant ist Serverbaum Rechte, Clientbaum Rechte, Servergruppenbaum Rechte und Channelgruppenbaum Rechte

**Comment by lgund** [comment]
Wird in der kommenden Version vorhanden sein!
