### ISSUE TITLE
Client Ban

### ISSUE THREAD

**Issue by rbardtke** [First-Coder/TS3-Webinterface#54]
wie sperrt das Webinterface die Nutzer?
In der DB steht unter benutzer_blocked "false". Ich komme mit meinem Admin Acc nicht mehr rein.
Passwort zurücksetzen bringt auch nichts.

**Comment by Provokan** [comment]
Wenn dies nichts bring eventuell eine Neuinstallation? Funktionierte dein Email-Client so das du die Email mit dem neuen PW erhalten hast?

**Comment by lgund** [comment]
Wenn der Benutzer mehrmals falsch eingegeben wurde, sie wird dieser lokal genannt. Dies geschiet über den browsercache. D.h. Ein einfacher browsercache clear sollte ausreichen. Wenn nicht geh mir hier bescheid, dann schaue ich mal :).

**Comment by lgund** [comment]
Ich gehe von aus, dass das Problem behoben ist?

**Comment by rbardtke** [comment]
jo alles wunderbar :)
Das mit dem Passwort zurücksetzen funktioniert, aber ich war im cache immer noch gebannt.
Deshalb konnte ich mich nicht einloggen.

**Comment by lgund** [comment]
Alles klar :) werde später noch ein faq erstellen, wo diese Probleme gelöst werden:)
