### ISSUE TITLE
XYZ E-Mail Adressen werden nicht akzeptiert

### ISSUE THREAD

**Issue by MrTwIXx** [First-Coder/TS3-Webinterface#57]
Hi,

Wenn ich meine XYZ E-Mail Adresse angebe, bekomme ich immer diese Meldung:  Fehlgeschlagen!
Interface Mail muss ein E-Mail sein!

Wie kann ich das beheben?

**Comment by lgund** [comment]
Es werden alle gangigen mails erlaubt. Dies würd über einen regulären Ausdruck geprüft. Allerdings ist es momentan nicht möglich, mails über die domain einzugehen. Z.b. Würde admin@first-coder.de nicht funktionieren. Dafür müsste in den js/webinterface/ alle js dateien durchsucht werden und dort der regex abgeandert werden.

Wie lautet denn die mail?

**Comment by MrTwIXx** [comment]
Es geht ums versenden über smtp.
Sie lautet noreply@twixx.xyz

**Comment by Provokan** [comment]
Hier gibt es bereits ein Tickets was dein Problem beheben sollten.

https://github.com/First-Coder/TS3-Webinterface/issues/35

**Comment by Sebbo94BY** [comment]
@lgund das hier ist die verwendete Regex, oder?

`regex=/^[-a-z0-9~!$%^&*_=+}{\'?]+(\.[-a-z0-9~!$%^&*_=+}{\'?]+)*@([a-z0-9_][-a-z0-9_]*(\.[-a-z0-9_]+)*\.(aero|arpa|biz|com|coop|edu|gov|info|int|mil|museum|name|net|org|pro|travel|mobi|[a-z][a-z])|([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}))(:[0-9]{1,5})?$/i`

Offiziell gibt es keine "Best Practices" Regex, die alle E-Mail Adressen auf ihre Gültigkeit prüfen kann. Aber diese hier wird für PHP sehr empfohlen:

`^(?!(?:(?:\x22?\x5C[\x00-\x7E]\x22?)|(?:\x22?[^\x5C\x22]\x22?)){255,})(?!(?:(?:\x22?\x5C[\x00-\x7E]\x22?)|(?:\x22?[^\x5C\x22]\x22?)){65,}@)(?:(?:[\x21\x23-\x27\x2A\x2B\x2D\x2F-\x39\x3D\x3F\x5E-\x7E]+)|(?:\x22(?:[\x01-\x08\x0B\x0C\x0E-\x1F\x21\x23-\x5B\x5D-\x7F]|(?:\x5C[\x00-\x7F]))*\x22))(?:\.(?:(?:[\x21\x23-\x27\x2A\x2B\x2D\x2F-\x39\x3D\x3F\x5E-\x7E]+)|(?:\x22(?:[\x01-\x08\x0B\x0C\x0E-\x1F\x21\x23-\x5B\x5D-\x7F]|(?:\x5C[\x00-\x7F]))*\x22)))*@(?:(?:(?!.*[^.]{64,})(?:(?:(?:xn--)?[a-z0-9]+(?:-[a-z0-9]+)*\.){1,126}){1,}(?:(?:[a-z][a-z0-9]*)|(?:(?:xn--)[a-z0-9]+))(?:-[a-z0-9]+)*)|(?:\[(?:(?:IPv6:(?:(?:[a-f0-9]{1,4}(?::[a-f0-9]{1,4}){7})|(?:(?!(?:.*[a-f0-9][:\]]){7,})(?:[a-f0-9]{1,4}(?::[a-f0-9]{1,4}){0,5})?::(?:[a-f0-9]{1,4}(?::[a-f0-9]{1,4}){0,5})?)))|(?:(?:IPv6:(?:(?:[a-f0-9]{1,4}(?::[a-f0-9]{1,4}){5}:)|(?:(?!(?:.*[a-f0-9]:){5,})(?:[a-f0-9]{1,4}(?::[a-f0-9]{1,4}){0,3})?::(?:[a-f0-9]{1,4}(?::[a-f0-9]{1,4}){0,3}:)?)))?(?:(?:25[0-5])|(?:2[0-4][0-9])|(?:1[0-9]{2})|(?:[1-9]?[0-9]))(?:\.(?:(?:25[0-5])|(?:2[0-4][0-9])|(?:1[0-9]{2})|(?:[1-9]?[0-9]))){3}))\]))$`

Rubular hat manchmal so diverse Probleme mit den Matches. Wenn du falsche der Reihe nach oben rauslöschst, siehst du, dass hier auch weiter oben, die richtigen matchen: http://rubular.com/r/ZxnbpM1WVF

Ich habe mal eben etwas kürzeres gebastelt:
`^([\w\.?\-\+]+@[\w\.\-\+]+\.[a-zA-Z]{2,4})$`

Diese scheint gut zu funktionieren, aber wie gesagt: Solche Prüfungen würde ich generall eher nicht machen, da du dir nie sicher sein kannst, dass es zu 100 % richtig funktioniert:  http://rubular.com/r/qHuYCMAeBP

Siehe "MATCH 5" in meinem Beispiel: Das ist keine gültige E-Mail Adresse - wird aber als solche markiert.

Tipp: Ich teste reguläre Ausdrücke immer gerne unter http://rubular.com/.

Alternativ gibt es von PHP eine fertige Funktion: http://php.net/manual/en/function.filter-var.php

Dieser erkennt aber auch nicht alles richtig, da sie sich anscheinend nicht an die RFC's lehnt.

Ich persönlich überlasse das prüfen dem HTML und vertraue dem. In meinen Applikationen muss sich der Benutzer normalerweise anhand einer E-Mail, die ihm zugesendet wird, verifizieren. Erhält er diese nicht, ist die E-Mail nicht gültig. ;)

Diese Seite erklärt eigentlich ganz gut anhand von einer Regex, wie eine E-Mail aufgebaut sein muss: http://emailregex.com/ :)

**Comment by lgund** [comment]
Sollte ich nun den regex ändern? Bin gerade verwirrt....

**Comment by MrTwIXx** [comment]
Aso ich habe es versucht ging trotzdem ned. Wenn ich auf diese emailrgex.xom Seite gehe wird meine E-Mail als E-Mail erkannt

**Comment by lgund** [comment]
Welchen regex würdest du versuchen?

**Comment by MrTwIXx** [comment]
Den General Email Regex...keine Ahnung ob der geht

**Comment by Sebbo94BY** [comment]
Am einfachsten den Filter nutzen. :)

**Comment by lgund** [comment]
> Am einfachsten den Filter nutzen. :)

Ein Beispiel? Würde es gerne mit JavaScript verwenden :)

**Comment by MrTwIXx** [comment]
Ja Server-Seitig musste auch :D

**Comment by lgund** [comment]
Aber regex ist doch ein Filter :)

**Comment by Sebbo94BY** [comment]
Ich würde es wie folgt lösen:

Client-seitig nutze einfach den HTML5 Input-Typ `email`: https://www.w3schools.com/html/html_form_input_types.asp

Und, um Server-seitig noch sicherzustellen, dass niemand den Input-Typen von `email` auf `text` abändert, um dann Mist einzugeben, würde ich einfach per PHP die Eingabe validieren.

Hierfür würde ich die PHP Funktion nutzen: http://php.net/manual/de/filter.examples.validation.php

Warum nicht `preg_match`, also eine Regex? Ganz einfach: Diese musst du permanent prüfen, testen und aktualisieren. Die fertigen PHP Funktionen werden von Entwicklern erstellt, die sich sehr gut mit der Materie auskennen und es auch entsprechend ausführlich testen. Wenn es Mist wäre, würde es auch nicht ins PHP Paket reinkommen. :)

Das Framework Laravel bietet hierfür z.B. fertige Funktionen: https://laravel.com/docs/5.4/validation#rule-email

**Comment by lgund** [comment]
Ist es auch mit JavaScript möglich? Ich schaue diese Woche mal ob s sowas auch gibt. Bin momentan leider nicht Mobil :)

**Comment by MrTwIXx** [comment]
Geht auch, dort isses aber auch wieder mit Regex :D  
Am besten wäre wirklich im HTML, musst ja nur den Input Type setzen und dann wie @Sebi94nbg gesagt hat mit der PHP Funktion.

**Comment by Sebbo94BY** [comment]
Bestimmt, aber warum möchtest du unbedingt JavaScript verwenden?

HTML5 bietet das Feature bereits bereits an. JavaScript muss man wahrscheinlich wieder mit einer Regex arbeiten, die nicht so gut funktioniert, wie die HTML5 Validierung.

JavaScript hat zudem den Nachteil, dass es zusätzlich geladen werden muss, da es extra eingebunden wird - wie ein Stylesheet z.B..

JavaScript kann - wenn es der User möchte - aber genauso deaktiviert / auskommentiert / abgeändert werden, wie HTML5. Insofern sehe ich überhaupt keinen Grund, warum man sich hier das Leben erschweren sollte, wenn es mit HTML5 ganz einfach zu lösen geht.

Zudem, wird es später wahrscheinlich so aussehen, dass HTML5 nur den Typen `email` benötigt und für JavaScript musst du wieder 5 Zeilen Code schreiben, die ggfs. so komplex aussehen, dass es nach einem Jahr z.B. wieder keiner versteht.

PS: Nicht alles, was es im WWW gibt, ist auch gut oder zu empfehlen. ;)

**Comment by lgund** [comment]
Das interface besteht zu einem großen teil aus javascript und das wird sich auch nicht ändern. Ich werde mir mal die validierung von html5 mal anschauen, allerdings könnte man diese doch bestimmt per dom aushebeln oder?

Ps nur der type email im input feld hilft nicht weiter, denn dieser ist schon seit 1.2.9 gesetzt. Dieser type hilft nur mobilen endgeräten die richtige Tastatur dazustellen.

**Comment by Sebbo94BY** [comment]
Alles, was Client-seitig ist, kannst du irgendwie aushebeln - auch JavaScript. Keine Frage.

Client-seitig stellt man normalerweise auch nur grobe Filter / Verhaltensregel auf und Server-seitig wird dann genauer geprüft und sichergestellt, dass alles korrekt eingegeben wurde.

Nein, das ist nicht ganz richtig. Der HTML5 Input-Typ `email` validiert auch die Eingabe an einem (unterstützten) mobilen und Desktop Browser und sagt, wenn diese z.B. keine gültige E-Mail Adresse ist.

Btw:

> Please do not use a pattern for email validation. Every regular expression for email validation is missing something. Lots of people gone through a process with the conclusion, that it is nearly impossible to get a perfect validation. The good part about is, we can leave this to our browser developers. They got it quite right and we should use their standard for email validation now.

Quelle: http://html5pattern.com/Emails

> There are two levels of content validation available for "email" inputs. First, there's the standard level of validation which is offered to all <input>s, which automatically ensures that the contents meet the requirements to be a valid email address. But there's also the option to add additional filtering to ensure that your own specialized needs are met, if you have any.

Quelle: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/email

**Comment by lgund** [comment]
Also type auf email setzen ist wie schon erwähnt getan. Allerdings wird die Abfrage per JavaScript abgefragt und nicht über ein submit Button. Von daher ist eine HTML 5 abfrage nicht möglich.

> Hierfür würde ich die PHP Funktion nutzen: http://php.net/manual/de/filter.examples.validation.php

Ich konnte mich hier nicht durchringen, diese Funktion zu verwenden, da diese wohl starke XSS Sicherheitsprobleme vorweist. Zudem ist diese Funktion für JavaScript nicht vorhanden. Das heißt, ich müsste hierzu einen neuen Ajax Request ausführen was wieder ein wenig Bearbeitungszeit benötigt.

Die Lösung des ganzen Problemes ist meinerseits einen einfachen JavaScript Regex. Des Weiteren habe ich diesen nun global definiert, dass dieser bei Wunsch zentral bearbeitet werden kann. Der Regex steht nun in der php/main/web_main.php. Ich werde später einen FAQ für´s Interface online stellen, wo alle solche Sachen beschrieben werden. Bevor es nun Beschwerden gibt, bitte ich einfach die Lösung einmal auszuprobieren und mir zu berichten, ob es so auch geht :).

Bitte laden sie folgende zip herunter und überschreiben die im zip befindlichen Dateien mit den Ihres Interfaces:
[https://teamspeak.first-coder.de/regexFix.zip](https://teamspeak.first-coder.de/regexFix.zip)

Gibt mir bescheid, ob dass das Problem löst. Dann werde ich diesen fix in Version 1.3.11 integrieren!

**Comment by lgund** [comment]
Ich gehe davon aus, dass das Problem damit behoben ist?
