### ISSUE TITLE
Allgemeines Problem bei Kundenansicht

### ISSUE THREAD

**Issue by MrTwIXx** [First-Coder/TS3-Webinterface#58]
Egal welche Berechtigungen der Kunde hat, wird er immer zur Dashboard Übersicht zurück geleitet. Bedeutet er kann gar nichts am Server machen.

**Comment by Provokan** [comment]
Kannst du uns ein paar mehr Details nennen, welche Version nutzt du?

**Comment by MrTwIXx** [comment]
Habe das Update von heute installiert also 1.3.10-OPEN-BETA.
Gestern ging es noch bei der alten Version

**Comment by MrTwIXx** [comment]
Fliege immer direkt vom web_teamspeak_serverview zu web_profil_dashboard zurück

**Comment by Provokan** [comment]
Fliegst du auch als eingeloggter "Admin" zurück oder nur als Kunde?

**Comment by MrTwIXx** [comment]
Nur als Kunde. Hab wieder das alte Interface raufgetan und es geht jetzt

**Comment by lgund** [comment]
Sind die rechte richtig gesetzt gewesen?

**Comment by MrTwIXx** [comment]
Glaub schon. Es geht jetzt wieder. Hatte vieleicht aufem Server falsche Rechte

**Comment by lgund** [comment]
Falls ein bug zu sein scheint, gebe mir bescheid :). Allgemein kannst du mir alle warnungen schicken, damit ich eine stäble machen kann :)
