### ISSUE TITLE
Passwort Reset über SMTP geht nicht

### ISSUE THREAD

**Issue by MrTwIXx** [First-Coder/TS3-Webinterface#59]
Ich habe es jetzt mal mit einer anderen E-Mail Adresse versucht. Jedoch kann ich das Passwort nicht zurücksetzen. Ich bekomme immer folgende Fehler Meldung "Password could not be resetted!"

Seit dem ich das Passwort zurücksetzen wollt, kann ich mich nicht mehr in den Admin Account einloggen.

Irgend eine Idee wie ich das Lösen kann?

**Comment by lgund** [comment]
Gibt es ein fehler in der system.log?

**Comment by MrTwIXx** [comment]
writeMail:SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

Aber nur wenn ich Port 465 verwende. Wenn ich Port 25 verwenden will, gibts keinen Fehler im System Log aber es geht trotzdem ned

**Comment by MrTwIXx** [comment]
Über Port 25 habe ich die Mails auf einmal erhalten, obwohl eine Fehlermeldung im Browser kam :D

**Comment by MrTwIXx** [comment]
Aso es geht nur über Port 25. Aber es kommt trotzdem eine Fehlermeldung

**Comment by Sebbo94BY** [comment]
Beachtet bitte, dass der SMTP Port 465 SSL benötigt - TLS funktioniert unter Umständen auch. Ist SSL nicht aktiviert/konfiguriert, wird das nicht funktionieren.

Der SMTP Port 25 funktioniert unverschlüsselt, ohne SSL, aber auch mit TLS Verschlüsselung.

**Comment by MrTwIXx** [comment]
Ja das is mir schon klar :D...aber mann kann ja nirgens SSL oder TLS auswählen. Da ich bisher immer SSL verwendet habe, habe ich es automatisch auch hier genommen

**Comment by Sebbo94BY** [comment]
Ja, da hast du wohl Recht.

@lgund kannst du bitte noch ein weiteres Feld bei der `config/config.php` ([Zeilen 48-L57](https://github.com/First-Coder/TS3-Webinterface/blob/1.2.9-OPEN-BETA/config/config.php#L48-L57)) hinzufügen?

`define("MAIL_SMTP_ENCRYPTION", "ssl"); // Possible values: off, tls, ssl`

**Comment by lgund** [comment]
Wird Mithilfe der verschlüsslung die Warnung behoben?

Werde es im kommenden update mit einpflegen :)

**Comment by Sebbo94BY** [comment]
Welche Warnung?

`writeMail:SMTP connect() failed.`

Das ist eine einfache Fehlermeldung: Nach dem Motto "Funktioniert so nicht.".

Und die nachfolgende Meldung, ist wohl etwas von dir bzw. deinem Webinterface:

`Password could not be resetted!`

**Comment by lgund** [comment]
Okey bitte einmal selbst austesten und mir bescheid geben, ob der Fehler immer noch auftaucht.

Config abändern wie @Sebi94nbg schon erklärt hat:

> @lgund kannst du bitte noch ein weiteres Feld bei der config/config.php (Zeilen 48-L57) hinzufügen?

define("MAIL_SMTP_ENCRYPTION", "ssl"); // Possible values: off, tls, ssl

Im Anschluss die folgende Datei herunterladen und mit der bestehenden im Interface ersetzen. Damit wird SMTPSecure entsprechend beim PHPMailer gesetzt:
[https://teamspeak.first-coder.de/smtpSslFix.zip](https://teamspeak.first-coder.de/smtpSslFix.zip)

**Comment by lgund** [comment]
Ich gehe davon aus, dass das Problem damit behoben ist?

**Comment by lgund** [comment]
Falls das problem ab v. 1.3.11 wieder auftritt, kann dieses issue wieder geöffnet werden.
