### ISSUE TITLE
1911#0: *3067 FastCGI sent in stderr: "PHP message: PHP Warning: in_array() expects parameter 2 to be array, null given

### ISSUE THREAD

**Issue by ghost** [First-Coder/TS3-Webinterface#6]
Steht in meinem Fehlerprotokoll wenn ich folgenden Link aufrufe

https://meineDeine.de/index.php?web_teamspeak_serverview?0?1

`1911#0: *3067 FastCGI sent in stderr: "PHP message: PHP Warning: in_array() expects parameter 2 to be array, null given in /var/www/vhosts/httpdocs/functions.php on line 513
PHP message: PHP Warning: in_array() expects parameter 2 to be array, null given in /var/www/vhosts/httpdocs/ts.server-msh.de/functions.php on line 513
PHP message: PHP Warning: in_array() expects parameter 2 to be array, null given in /var/www/vhosts/httpdocs/ts.server-msh.de/functions.php on line 513
PHP message: PHP Warning: in_array() expects parameter 2 to be array, null given in /var/www/vhosts/httpdocs/ts.server-msh.de/functions.php on line 513
PHP message: PHP Warning: in_array() expects parameter 2 to be array, null given in /var/www/vhosts/httpdocs/ts.server-msh.de/functions.php on line 513
PHP message: PHP Warning: in_array() expects parameter 2 to be array, null given in /var/www/vhosts/httpdocs/ts.server-msh.de/functions.php on line 513
PHP message: PHP Warning: in_array() expects parameter 2 to be array, null given in /var/www/vhosts/httpdocs/ts.server-msh.de/functions.php on line 513
PHP message: PHP Warning: in_array() expects parameter 2 to be array, null given in /var/www/vhosts/httpdocs/ts.server-msh.de/functions.php on line 513
PHP message: PHP Warning: in_array() expects parameter 2 to be array, null given in /var/www/vhosts/httpdocs/ts.server-msh.de/functions.php on line 513
PHP message: PHP Warning: in_array() expects parameter 2 to be array, null given in /var/www/vhosts/httpdocs/ts.server-msh.de/functions.php on line 513
PHP message: PHP Warning: in_array() expects parameter 2 to be array, null given in /var/www/vhosts/httpdocs/ts.server-msh.de/functions.php on line 513" while reading response header from upstream`

**Comment by lgund** [comment]
Ist das nur eine Warnung? Oder hat die Seite auch ein Problem / Fehler?

**Comment by ghost** [comment]
Nein auf der Seite selber gibt es keine Fehler.

**Comment by lgund** [comment]
Ok werde es ist der nächsten version gefixt haben. Danke für die info :)

**Comment by lgund** [comment]
#fixed in the version 1.1.9
