### ISSUE TITLE
Log flood

### ISSUE THREAD

**Issue by lgund** [First-Coder/TS3-Webinterface#61]
Version 1.3.11 has a lot of notices in the logs. In the next version will be all Notices disabled. Warnings and errors will stay activated.

**Comment by lgund** [comment]
Fixed in Version 1.3.12

**Comment by Sebbo94BY** [comment]
What about an option to set a log level using the config file?
```
/*
	Log settings
*/
define("LOG_LEVEL", "warn"); // Possible values: debug, info, notice, warn, error
```
| Log Level | Description |
| --- | --- |
| debug | All messages |
| info | Information messages |
| notice | Normal, but significant state |
| warn | Warning messages |
| error | Error messages |

The higher the log level (`error` is the highest) is, the lesser messages will be logged.

When you set `debug`, it will log all messages (debug, info, notice, warn and error). When you set `notice`, it will only log these and higher messages (notice, warn and error). So, when you set `error`, it will only log error messages.

**Comment by lgund** [comment]
Normaly yes :). But the system logs from the apache user are flooded. I just need to fix them. A second solution would be change `error_reporting` off. But it´s a dirty solution.
