### ISSUE TITLE
Update Rollout , Interface ?

### ISSUE THREAD

**Issue by ragman104** [First-Coder/TS3-Webinterface#63]
Moin,

Mal eine Frage, gibts es eine regel/Intervall wann ein Veröffentlichstes Updated auch über das Interface Installierbar ist ? Da liegen ja schonmal ein paar Tage dazwischen.

gruß
Mike

**Comment by SoulofSorrow** [comment]
Sobald das update online ist bekommen es spender direkt, alle anderen 2 wochen danach

**Comment by ragman104** [comment]
ahhh ok, dachte ich mir fast wollt eh mal ne spende machen noch ein grund mehr;)

**Comment by SoulofSorrow** [comment]
Das freut uns ;).... Zusätzlich tust du noch etwas für das allgemein wohl sobald das spendenziel erreicht ist wird die v2 veröffentlicht ;)

**Comment by ragman104** [comment]
Nochmal kurz nachgefragt, wie kommen die Donater dann ich sage mal zu ihrem vorab Service ;) ?? Weil Donaten Done ;) vieleicht Dokumentiert man das mal irgendwo , wenn schon passiert und ich nur zu blöde es zu finden dan Sorry ;)

**Comment by SoulofSorrow** [comment]
Hey schau mal in dir Datei /config/config.php
An der vorgesehen stelle deine PayPal emailadresse mit der du bezahlt hast eintragen 

Unter define("DONATOR_MAIL", "example@first-coder.de")

**Comment by ragman104** [comment]
Top, danke hat Funktioniert.
