### ISSUE TITLE
Update Info Fehler

### ISSUE THREAD

**Issue by NewGothic** [First-Coder/TS3-Webinterface#64]
Wenn man über die Webseite die aktuelle Version 1.3.11 runterläd bekommt man die Info das die Version Veraltet ist und das Interface will V. 1.3.10 als Version Installieren was ja Veraltet ist von der Version. 

Ohne Donate eintragung im System.

**Comment by SoulofSorrow** [comment]
Das letzte update gab es ohne Freischaltung.
Warum er das update downgraden will kann ich momentan nicht beantworten. 
Ich nehme sofort Kontackt zu first-coder auf

**Comment by NewGothic** [comment]
Ich weiß habe gestern schon mit Lukas geschrieben sollte es nur hier noch mal posten damit es nicht verloren geht ;)

**Comment by SoulofSorrow** [comment]
Okayy

**Comment by lgund** [comment]
Bitte issue auf lassen, muss ich noch beheben. 

Für nicht "donator" ist die neuste verseion 1.3.11 noch nicht bekannt. Daher will das interface zu einer bekannten version wechseln. Dieses Phänomen wird nach 2 wochen aufhören. 

Wird auf jeden fall in version 1.3.12 behoben werden!

**Comment by lgund** [comment]
Fixed in Version 1.3.12
