### ISSUE TITLE
I have problem with menu afret log-in

### ISSUE THREAD

**Issue by Davvid77** [First-Coder/TS3-Webinterface#67]
Hello.
I have a problem with the menu, because all links in php have bounced me to the left and nothing on my right. This also prevents editing of most things, so please help. This is screenshot: https://snag.gy/ywJajL.jpg

**Comment by Sebbo94BY** [comment]
Hey,
your installation misses some CSS ressources, that's the reason, why it looks like that.

Please make sure, that all ressources are available on your server. Your installation misses these files:
* css/styleNexusNavigation.css
* css/style.css

**Comment by Davvid77** [comment]
Actually missing these two files, thank you for the help :) Regards

**Comment by lgund** [comment]
Thanks sebbi for your fast help :). @Bezolowsky, if this problem is fixed, please close this issue.
