### ISSUE TITLE
Serverbanner zeigt nichts an

### ISSUE THREAD

**Issue by MrTwIXx** [First-Coder/TS3-Webinterface#68]
Hallo zusammen,

War in den Ferien darum konnte ich auf die letzten Issues nicht mehr Antworten, aber es wurde ja alles behoben.

Leider wird mir immer nur der leere Serverbanner angezeigt, auch wenn ich Texte hinzufüge und danach auf "Speichern" drücke.
Habt ihr eine Idee an was es liegen kann?

**Comment by SoulofSorrow** [comment]
Hast du in den logs etwas gefunden

**Comment by SoulofSorrow** [comment]
Bzw hast du den richtigen Link, logs kontrollieren und prüfen ob er die Banner Einstellungen auch geschrieben hat /Images/ts_banner/0_9987_settings.json und 0_9987_cached_img

**Comment by lgund** [comment]
Bitte schreib mal hier den Inhalt der .json Datei hinein. Damit wir feststellen können, ob die Koordinaten gespeichert wurden.

**Comment by MrTwIXx** [comment]
@lgund Was für eine .json Datei?

@SoulofSorrow Habe den Link vom Iframe. In welchen Logs? Im Ordner Logs sind nur leere Files drin.

**Comment by SoulofSorrow** [comment]
In den Apache2/nginx/iis logs je nachdem was du nutzt

**Comment by MrTwIXx** [comment]
Aso im .json File sind die Angaben eingetragen.
Hier das ganze File:
`{"settings":{"bgimage":"./images/ts_banner/default_banner.png"},"data":{"%servername%":{"x":82.75,"y":424,"fontfile":"./fonts/neuropoliticalrg.ttf","fontsize":"24","color":"#ff0000","text":""},"%ping%":{"x":97.75,"y":293,"fontfile":"./fonts/neuropoliticalrg.ttf","fontsize":"24","color":"#ff0000","text":""}},"custom":{}}`

**Comment by SoulofSorrow** [comment]
Das siehst Schonmal gut aus. 
Jetzt die webserver logs?

**Comment by MrTwIXx** [comment]
Hier:
` - - [09/Aug/2017:12:57:06 +0200] "GET /iframeServerBanner.php?port=9987&instanz=1 HTTP/1.1" 200 276613 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
- - [09/Aug/2017:12:57:07 +0200] "POST /php/functions/functionsSqlPost.php HTTP/1.1" 200 551 "https://ts3.twixx.xyz/index.php?web_teamspeak_serverbanner?1?1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
- - [09/Aug/2017:12:57:07 +0200] "POST /php/functions/functionsSqlPost.php HTTP/1.1" 200 2434 "https://ts3.twixx.xyz/index.php?web_teamspeak_serverbanner?1?1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
- - [09/Aug/2017:12:57:07 +0200] "POST /php/functions/functionsSqlPost.php HTTP/1.1" 200 2434 "https://ts3.twixx.xyz/index.php?web_teamspeak_serverbanner?1?1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
- - [09/Aug/2017:12:57:07 +0200] "POST /php/functions/functionsSqlPost.php HTTP/1.1" 200 2959 "https://ts3.twixx.xyz/index.php?web_teamspeak_serverbanner?1?1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
- - [09/Aug/2017:12:57:07 +0200] "POST /php/functions/functionsSqlPost.php HTTP/1.1" 200 1076 "https://ts3.twixx.xyz/index.php?web_teamspeak_serverbanner?1?1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
- - [09/Aug/2017:12:57:07 +0200] "POST /php/functions/functionsSqlPost.php HTTP/1.1" 200 1076 "https://ts3.twixx.xyz/index.php?web_teamspeak_serverbanner?1?1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"`

**Comment by SoulofSorrow** [comment]
Nächste mal gerne als Pastebin Link.
Wir brauchen die error log.
Kannst mir auch privat per telegramm oder email zukommen lassen

**Comment by MrTwIXx** [comment]
Hier der Pastebin Link :D https://pastebin.com/19FYBvuD

**Comment by lgund** [comment]
Ok da steht ja der Fehler, dass data aus irgendeinem Grund undefinied ist. Kannst du mir mal bitte den Inhalt von der iFrameServerbanner.php schicken?

**Comment by MrTwIXx** [comment]
Hier: https://pastebin.com/7Qj0PbUw

**Comment by lgund** [comment]
Welche Version nutzt du? Ich habe den Fehler gefunden und war mir sicher, dass dieser schon behoben wurde...

**Comment by lgund** [comment]
Also Zeile 94, sowie Zeile 98 musst du das Array folgendermaßen ändern. Du siehst dort doch immer "[0]". Das musst du ändern in "[$instanz]". Insgesamt solltest du es vier mal geändert werden. Danach sollte es gehen 👍 .

Wird in der Version 1.3.14 gefixt!

PS Bitte gebe mir eine Info, ob es geklappt hat.

**Comment by MrTwIXx** [comment]
Perfekt danke, funktioniert jetzt. 
Benutze 1.3.11-OPEN-BETA

**Comment by lgund** [comment]
Alles klar... Bei den nächsten 2 Updates wird es leider wieder fehlerhaft eingefügt. Ich werde es erst in der 1.3.14 gefixt haben. Also wenn du updatest musst du vorerst die Datei wieder manuell bearbeiten wie gerade auch.

Falls noch irgendwelche Fragen oder Probleme auftauchen, so öffne dieses Issue wieder :)
