### ISSUE TITLE
unsauberes Coding

### ISSUE THREAD

**Issue by osnet** [First-Coder/TS3-Webinterface#7]
> Warning: Illegal string offset 'id' in /var/www/teamspeak_cp/web_main.php on line 47
> Notice: Undefined index: login in /var/www/teamspeak_cp/web_main.php on line 54
> Notice: Undefined index: HTTP_REFERER in /var/www/teamspeak_cp/web_main.php on line 69
> Notice: Undefined offset: 2 in /var/www/teamspeak_cp/web_main.php on line 70
> Notice: Undefined offset: 3 in /var/www/teamspeak_cp/web_main.php on line 71

Infolge dessen  dreht sich der Loader nen Wolf ... 

Frische installation  direkt von der seite runter.
apache und php5.7  unter Centos7 x64, MariaDB

**Comment by lgund** [comment]
Ich werde diese Warnungen in der nächsten version entfernen. Danke schon mal dafür :). Allerdings sind die nicht der grund das der preloader sich aufhängt....

**Comment by osnet** [comment]
mmh  interessant.  ja  habe mich  falsch ausgedrückt.  ich  schiebe das mal auf nen  normalen  webspace hoch.  wenns da geht, dann ist meine  DEV  umgebung h ier nicht  für dein zeug  gemacht ^^

**Comment by lgund** [comment]
XD mein zeug! ... Ja ich bin gerade allgemein dabei die ganzen warnungen zu beheben und die performance an sich zu bessern. Daher heißt das ding na auch noch beta ^^

**Comment by BloodDragon2580** [comment]
Bei mir bleibt es auch im Lade Screen hängen wenn ich mich einloggen möchte.
Egal ob mit php5 oder php7^^.  freu mich schon drauf wenn es richtig funktioniert. Endlich mal ein Interface mit style.

**Comment by osnet** [comment]
mein ja nur : )) 
auf einer standard  Plesk maschine rennt das ding ohne probleme ...

**Comment by BloodDragon2580** [comment]
Habe auch Plesk Odin mit Windows.
Lass dich nicht hetzen das wird schon noch.^^

**Comment by osnet** [comment]
sowas gibts ? ernsthaft ?  interessante sache  also  plesk mit centos  kein ding

**Comment by lgund** [comment]
> Warning: Illegal string offset 'id' in /var/www/teamspeak_cp/web_main.php on line 47

#fixed

> Bei mir bleibt es auch im Lade Screen hängen wenn ich mich einloggen möchte.
Egal ob mit php5 oder php7^^. freu mich schon drauf wenn es richtig funktioniert. Endlich mal ein Interface mit style.

Scheint ein anderes Problem zu sein, was sagen die logs?

**Comment by BloodDragon2580** [comment]
user.log
2017-01-23 21:25:37	NOTICE		xxxxx@gmail.com: Is logging in!

System.log
ist nichts.

Bleibt einfach beim lade screen hängen.^^

![unbenannt](https://cloud.githubusercontent.com/assets/1429236/22236383/8c2a2aa4-e205-11e6-9f14-43881f9dc5b0.jpg)

**Comment by osnet** [comment]
der unteschied zwischen meinem  centos  hier im lan  und dem auf der plesk maschine ist  das auf  plesk  php  fcgi rennt , hier nicht

**Comment by lgund** [comment]
@DarkBrain, könntest du in den apache logs nachschauen welcher fehler vorliegt? In der neuen version die in den nächsten Tagen kommt ändert sich ein wenig am dashboard, vllt behebt das schon den Fehler, aber will da lieber sicher gehen :)

**Comment by BloodDragon2580** [comment]
Habe IIS von apache finde ich nichts genauso wenig tomcat.

**Comment by lgund** [comment]
Es müssen doch logs existieren...

**Comment by BloodDragon2580** [comment]
mit der neuen version gehts jetzt ohne probleme.

**Comment by lgund** [comment]
Sehr gut das freut mich wirklich 👍 ein Schritt näher zur stable!

Vielen Dank für deine Gedult!

**Comment by BloodDragon2580** [comment]
sagte ja immer mit der ruhe lass dich nicht abhetzen.^^
