### ISSUE TITLE
TSDNS Modul

### ISSUE THREAD

**Issue by MrTwIXx** [First-Coder/TS3-Webinterface#70]
Hallo zusammen,

Wäre es möglich, dass man TSDNS Modul einbauen kann? Dort soll der User von verschiedenen vorgegebenen Domains seine Subdomain für den Teamspeak erstellen können.

LG
TwIXx

**Comment by lgund** [comment]
Ja das ist nicht nur möglich, das ist geplant! Allerdings wird dies ein Feature der Version 2 werden, da dafür ein Bot benötigt wird :+1:

**Comment by MrTwIXx** [comment]
Super. Also wie willst du das machen? Weil im Teamspeak Forum steht, dass TSDNS allenfalls eingestellt wird.

**Comment by lgund** [comment]
Mir ist neu das TSDNS abgeschafft werden soll. Wenn Teamspeak selbst die Funktion einstellt muss ich mir was überlegen, aber ich weiß das ich es hinbekommen werde.

Ich kann jedenfalls schon soviel sagen, dass ich den TSDNS, der im Teamspeakverzeichnis abgelegt ist, nicht verwenden werde. Es ist vielmehr geplant einen eigenen selbstständigen Dienst zu entwickeln.

**Comment by MrTwIXx** [comment]
Man kann ja einfach A und SRV Records erstellen. Versuche mal über die Cloudflare API so nen kleinen DIenst aufzustellen :D 
Hier noch der Link zum Forum: http://forum.teamspeak.com/threads/130464-TSDNS-Support

**Comment by lgund** [comment]
Ich werde zu diesem Thema zurück kommen, sobald das Hauptbot des Interfaces steht. Dieser steuert primär alles, was im Background passiert. Sprich folgende Sachen:

1. Querybot Funktionen, wie AFK move, sticky channel .....
2. Statistik Funktionen, wie Ranksystem, Traffic- bzw, Userdiagramme....
3. Musicbot! Ja der Querybot steuert den Musicbot an!
4. TSDNS

**Comment by lgund** [comment]
I’m not sure if I can in the current state promise that I will create a tsdns Modul. We need to wait until we know what teamspeak will make with her tsdns service in 3.1.

I hope we can find a way to manage this ;).

Dear
Lukas

**Comment by MrTwIXx** [comment]
@lgund 

Is verständlich. Kannst du ein Request Formular machen, bei welchem die User einen A Record Requesten können. Aso der Admin kann die Domains einstellen und der User den Subdomain Namen.

Das ersetzt ja sotzusagen dann das TSDNS Modul

**Comment by lgund** [comment]
Da müsste ich mich mal schlau machen. Ich werde aber vorerst auf Version 3.1 warten, da es eventuell auch damit nicht mehr möglich sein kann. So wie ich es momentan verstanden habe, wird es so sein, dass du bei Teamspeak selbst deine Ip-Adresse mit einem Nameserver versehen musst. Eigentlich schwer denkbar, da Teamspeak ja weiterhin (hoffentlich) über ein Port arbeiten muss. Allerdings weiß ich momentan nicht genau was kommen wird.

Ich denke mal du meinst, das der IP:PORT von dem Teamspeakserver über den Record Nameserver der Domain eine subdomain erhält. Soweit korrekt?

**Comment by MrTwIXx** [comment]
Genau das meine ich. So mache ich es auch mit meinem eigenen Server. Ist halt etwas aufwendiger, da man es immer per Hand machen muss.

Finde es halt noch gut, dann kann man die Domain über Cloudflare laufen lassen und so ist auch die IP des Servers nicht einsehbar :D

**Comment by lgund** [comment]
Das ist korrekt.. Hoffen wir mal, dass die Entwickler von Teamspeak mit ihrer 3.1 nicht alles kaputt machen. Würde ungern sehen wie Teamspeak und eben auch mein Projekt ausstirbt 👎

**Comment by lgund** [comment]
Mit Teamspeak 3.1 würde das TSDNS Modul leider verabschiedet.
