### ISSUE TITLE
Fehlgeschlagen! web_teamspeak_server_requests

### ISSUE THREAD

**Issue by brudermafia1** [First-Coder/TS3-Webinterface#71]
Bekomme die seit paar tagen  Fehlgeschlagen!
wenn ich es auf Server erstellen klicke geht das nicht bekomme immer wieder diese meldung. was kann die ursachen haben da ich mit den Web Interface Psychokiller  getestet habe geht.
 nur in von ihre Webinterface geht das auf einmal nicht mehr.
 Fehlgeschlagen!
ErrorID: 1540 | Message: convert error

Versioninformationen
Installierte Version: 1.3.12-OPEN-BETA
Neuste Version: 1.3.11-OPEN-BETA

**Comment by lgund** [comment]
Die Nachricht sagt aus, das die daten nicht richtig an dir query Konsole übertragen wurde. Es wird wohl ein bug sein und werde es mir anschauen. Ich gebe bescheid, sobald ich näheres weiß.

Tritt der Fehler beim Server erstellen und Serverantrag auf?

**Comment by brudermafia1** [comment]
danke ihnen lgund
Dieser fehler kommt wenn man Serveranträge
https://prntscr.com/g7a5z9
https://prntscr.com/g7a5wv
ich hoffe das die bilder ihnen weiterhelfen werden
MFG
BruderMafia

**Comment by SoulofSorrow** [comment]
Bei mir tritt das Problem nicht auf.
Hast du die error logs? 
Gerne stehe ich auch per telegram zur Verfügung

**Comment by brudermafia1** [comment]
meinten sie vielleicht den Systemlogs 

Datum2017-08-05 08:55:22LoglevelINFOBeschreibunggetUserInformations: User not found!
--
Datum2017-08-05 08:56:32LoglevelINFOBeschreibunggetUserInformations: User not found!
Datum2017-08-05 08:57:49LoglevelINFOBeschreibunggetUserInformations: User not found!
Datum2017-08-09 13:35:19LoglevelINFOBeschreibunggetUserInformations: User not found!
Datum2017-08-10 14:13:56LoglevelINFOBeschreibunggetUserInformations: User not found!


Ich habe vergessen zu schreiben auf welchen Betriebssystem das ist

Servertyp | Root Server M 2.0
Betriebssystem | Debian 8 (64bit)
Admintool | Plesk
Hostsystem | rsh084 (Linux)

**Comment by brudermafia1** [comment]
Ich habe vergessen zu schreiben auf welchen Betriebssystem das ist

Servertyp | Root Server M 2.0
Betriebssystem | Debian 8 (64bit)
Admintool | Plesk
Hostsystem | rsh084 (Linux)

**Comment by brudermafia1** [comment]
Guten morgen
Habe den fehler gefunden das lag an bei config.php host banner wenn man den wieder rausnimmt den link geht das an bei frei wider, aber wenn man den link wider rein tut geht das nicht mer .

```
	$ts3_server_create_default['host_banner_url']					=	'https://image.prntscr.com/image/Ii8uesRrSLS9K7t6kgHvNQ.png';
	$ts3_server_create_default['host_banner_int']					=	'https://testdemo.de';
```

**Comment by lgund** [comment]
Ja das ist in diesem Fall auch logisch. Denn `$ts3_server_create_default['host_banner_int']` ist, wie der Vektor schon sagt von Typ integer. Das heißt dort wird ein Zahlenwert erwartet. Wenn dort nun natürlich ein String eingetragen wird, so wird dieser als Konvertierungsfehler angesehen, da man diesen nicht als Zahl umwandeln kann.

**Comment by brudermafia1** [comment]
ja habe es vorher nicht beachtet so besonders auf die befehle tut mir leid @lgund  .
