### ISSUE TITLE
Installation: Tabelle 'main_rights' konnte nicht erstellt werden

### ISSUE THREAD

**Issue by Jniklas2** [First-Coder/TS3-Webinterface#73]
Da ich meinen Server neu aufgesetzt habe, musste ich auch das Webinterface neuinstallieren, nun bekomme ich aber beim Datenbank erstellen diesen Fehler 
![image](https://user-images.githubusercontent.com/18490197/31311076-eed844b0-aba4-11e7-9f1e-a8a76af0fadf.png)
 Ich habe Debian 9.1 mit MariaDB 10.1.26-MariaDB-0+deb9u1 und PHP 7.0.19-1. 

Hoffe jemand kann mir irgendwie dabei helfen
MfG Jniklas2

**Comment by lgund** [comment]
Der Fehler ist schon hin und wieder aufgetreten. Ich selbst hatte leider keine Zeit in zu fixen. Es geht darum, dass die Datenbank zu groß ist. Dies könnte man bestimmt in den sql Einstellungen ändern, allerdings ist dies keine gute Idee denke ich. Falls das ok ist,könntest du diese fummelarbeit übernehmen. Folgendes müsste gemacht werden .....

1. Rufe die Installation bis zum Fehler auf...
2. öffne die /install/functionsPost.php mit notepad o.ä.
3. Dort gibt die Funktion create database und dort wird die main_clientd erstellt. Es werden dort alle Felder meistens mit 255 Felder erstellt. Man kann diese allerdings runtersetzen :).

**Comment by Sebbo94BY** [comment]
Hier sind ein paar Lösungsvorschläge:
* https://stackoverflow.com/questions/30761867/mysql-error-the-maximum-column-size-is-767-bytes
* https://stackoverflow.com/questions/42043205/how-to-fix-mysql-index-column-size-too-large-laravel-migrate

**Comment by lgund** [comment]
Ich werde versuchen bis morgen ein fix bereit zu stellen. Ich denke das es einfach zu beheben ist.

Tut mir leid, dass ich nicht eher antworten konnte, allerdings wollte ich gestern unbedingt den installer für v2 fertig schreiben.

Mit freundlichen Grüßen
Lukas

**Comment by Jniklas2** [comment]
@lgund Kein Problem, ich habe erstmal die Werte in der /install/functionsPost.php herunter gestellt. 
@Sebi94nbg Danke für die Links, ich bin auch bei meiner Recherche auf die gestoßen, aber ich habe das trotz dem aktivieren den Fehler gehabt.

**Comment by lgund** [comment]
> Kein Problem, ich habe erstmal die Werte in der /install/functionsPost.php herunter gestellt.

Hat es denn funktioniert?

**Comment by lgund** [comment]
Ich habe nun mal die Datenbank Felder logisch verkleinert und hoffe das nun alles klappt. Könntest du es bitte für mich testen, damit ich Gewissheit habe?

[install.zip](https://github.com/First-Coder/TS3-Webinterface/files/1382578/install.zip)

Mit freundlichen Grüßen
Lukas

**Comment by Jniklas2** [comment]
habs gerade einmal damit gemacht und es funktioniert ohne Probleme, und vorher als ich die Werte heruntergestellt hatte, hat es auch funktioniert.

**Comment by lgund** [comment]
Alles klar! Ich werde es in der v2 und ab der v1.3.15 integrieren! Danke für den Bug report... sollte einer der letzten für v1 gewesen sein 👍

**Comment by Jniklas2** [comment]
Mir ist gerade noch ein kleiner Rechtschreibfehler im Webinterface aufgefallen:
![image](https://user-images.githubusercontent.com/18490197/31551066-bf89ce66-b033-11e7-9b64-2de48a597605.png)
wird das nicht "coming soon" geschrieben? Also mit einem m?

**Comment by lgund** [comment]
Ja da hast du recht.. ich und meine Rechtschreibung 👎 . Da in v1 der Bot nicht mehr integriert werden wird, wird in der neuen Version die Box sowieso entfernt. Ich dachte allerdings, dass ich das nicht schon gemacht hatte.... 

Trotzdem danke für den Hinweis!
