### ISSUE TITLE
PHP error: Undefined index: user

### ISSUE THREAD

**Issue by Bluscream** [First-Coder/TS3-Webinterface#74]
When i click on install nothing happens and my apache error.log shows
```
[Tue Oct 17 01:37:35.278638 2017] [php7:notice] [pid 5212:tid 1932] [client 127.0.0.1:4278] PHP Notice:  Undefined index: user in S:\\XAMPP\\htdocs\\webi\\php\\functions\\functionsPost.php on line 43, referer: http://localhost/webi/
[Tue Oct 17 01:37:35.279138 2017] [php7:notice] [pid 5212:tid 1932] [client 127.0.0.1:4278] PHP Notice:  Undefined index: user in S:\\XAMPP\\htdocs\\webi\\php\\functions\\functions.php on line 304, referer: http://localhost/webi/
```

**Comment by lgund** [comment]
Hey,

Looks like I’ve forgotten some warnings. They will be removed in the next update, but it shouldn’t be a reason why it won’t work. Did you see the notice on the homepage? If yes please deactivate error_display in your php.ini. Then it should work!

Dear
Lukas

**Comment by Bluscream** [comment]
Now the notices are gone but the webinterface still does nothing :/

**Comment by lgund** [comment]
You have disabled display_errors and restarted the webserver?

**Comment by Bluscream** [comment]
Yes, i uncommented it and restarted apache

**Comment by lgund** [comment]
Hmm, that’s strange. Is it possible to give me the link where the interface is installed? Maybe I can find something.

**Comment by Bluscream** [comment]
Its local for now, i wanted to test it first before i use it productional (security is important u know ^^)

**Comment by lgund** [comment]
Sure, if you find security bugs, please let it me know. 

My idea why nothing happens is, that the Ajax request doesn’t get done as return. There might be some notice and after the notice comes the done. If I’m not wrong you are also a developer in splamys team, right? So just check what comes back if you click on the install button (from the Ajax request). The JavaScript file for this should be in the install folder.

Dear
Lukas

**Comment by lgund** [comment]
Did you found something?
