### ISSUE TITLE
SEND_VERSION will be removed

### ISSUE THREAD

**Issue by Sebbo94BY** [First-Coder/TS3-Webinterface#75]
From your Changelog:
> **ver. 1.3.15-STABLE**
> - SEND_VERSION will be removed. Version will now always saved just for statistics

I wouldn't remove this. The user should always have the ability to allow or disallow specific things. Especially remote connections to other servers. The user should also be able to decide, if the web interface should be able to check, if there is a newer version of the web interface or not.

Due of that, that it's OpenSource, everyone can change the code to disable such features, but this may also cause more support requests for you. So I rather would add it and set the defaults to `true`.

Some people like me for example expect, that such web interfaces do not communicate with anything else than the configured TeamSpeak 3 server for example. If it does, I would block every traffic using firewall rules or by updating the source code, because in my opinion it's not required.

**Comment by lgund** [comment]
I totally understand what you mean. I wouldn’t also remove this feature, but I’ve seen that the clients that using this interface are disabled this sen_version. It wouldn’t be a problem, but when it over 80 percent does, I can throw my statistics into trash.

That’s why I removed this. But I will think about to reactivate it again.
