### ISSUE TITLE
Datenbankeinträge werden nicht erstellt

### ISSUE THREAD

**Issue by mumi** [First-Coder/TS3-Webinterface#76]
Bei der Installation der Webinterfaces, zeigt die Konsole im Abschnitt Datenbankverbindung nur "Creating..."
Inwiefern es mit der Nutzung von nginx als Webserver zusammenhängen könnte, kann ich mir nicht erklären, ihr vielleicht.

**Comment by lgund** [comment]
Da die Datenbankverbindung erfolgreich war, wird es sich hierbei um ein flood ban handeln. Hast du schon mal versucht für die Zeit der Installation die Firewall auszuschalten?

Mit freundlichen Grüßen
Lukas

**Comment by mumi** [comment]
Web und TS server sind auf dem gleichen Host, flood ban schließe ich auch aus, weil ich nach einem reload der Seite direkt wieder eine Datenbankverbindung aufbauen kann.
Was mir jetzt zufällig aufgefallen ist, dass der Seitenname mit Databaseerror endet ([https://i.imgur.com/nWldwSf.png](url)). Vermutlich nur weil die Datenbank bereits in die config eingetragen wurde, die Datenbank jedoch leer ist.

**Comment by lgund** [comment]
Die Vermutung mit der Datenbank ist korrekt.

Ich sende bei der Installation viele datenbankbefehle auf einmal, sicher das diese nicht geblockt werden? Kommt bei deinem php error log irgendwelche Fehler?

**Comment by mumi** [comment]
`2017/11/17 21:44:09 [error] 8636#0: *25 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [1045] Access denied for user 'c2ts3'@'localhost' (using password: YES)' in /var/www/clients/client2/web7/web/install/functionsPost.php:228
Stack trace:
#0 /var/www/clients/client2/web7/web/install/functionsPost.php(228): PDO->__construct('mysql:host=loca...', 'c2ts3', 'PASSWORT')
#1 {main}
  thrown in /var/www/clients/client2/web7/web/install/functionsPost.php on line 228" while reading response header from upstream, client: MEINE-IP, server: example.com, request: "POST /install/functionsPost.php HTTP/1.1", upstream: "fastcgi://unix:/var/lib/php5-fpm/web7.sock:", host: "example.com", referrer: "https://example.com/"
`

So sieht die log danach aus.. Also irgendwie denied er den Zugang, bei Zeile 228 functionsPost.php.

**Comment by gOOvER** [comment]
Kein fehler vom Script. ;)

"SQLSTATE[HY000] [1045] Access denied for user 'c2ts3'@'localhost'"

Liegt bei Dir. Sind falsche MySQL Daten hinterlegt

**Comment by mumi** [comment]
Nein definitiv nicht. Er kommt ja durch den "Datenbank prüfen" Button, hab mehrmals das Passwort geändert und mit einem anderen Skript auch mal getestet.

**Comment by lgund** [comment]
Wie schon gesagt, bin mir sicher das die Firewall einfach die Verbindungen für den Bereich loggt, da zu viele Befehle auf einmal kommen. Wir reden hier von ~40 Befehlen in 1 sek.

**Comment by mumi** [comment]
Wordpress schafft es ja auch ohne flood ban,falls es überhaupt das problem sein sollte :) Kannst du die SQL Datenbank als backup datei rüberschicken, damit ich es manuell einspeise?

**Comment by lgund** [comment]
Leider kann ich das nur bedingt, da individuelle keys in der Datenbank eingetragen werden. Wenn du willst kann ich dir trotzdem ne backup datei geben, insofern diese datei nur zu testzwecken gebraucht wird....

Ich habe ab der v2 auch im installer eingeschrieben, dass er für jeden Befehl 1 sek warten soll, damit kein ban passiert...

**Comment by mumi** [comment]
Jo gerne.

Wann ist der Release von v2 geplant?

**Comment by Sebbo94BY** [comment]
@lgund: Monitoring Lösungen führen +200 Befehle pro Sekunde aus und haben keine Probleme. ;)

**Comment by Sebbo94BY** [comment]
Das selbe Problem hat noch jemand: #77

**Comment by Sebbo94BY** [comment]
@mumi hast du auch ein Sonderzeichen in deinem Passwort? Aktuell wird das wohl durch HTML-Code ersetzt und dementsprechend ist es danach ungültig.

**Comment by mumi** [comment]
Tatsächlich. Das war der Fehler :D 
Hoffentlich wird das schnellstmöglich debuggt.

**Comment by lgund** [comment]
Fehler wurde nun behoben und ist bei einem neuen Download integriert. Danke für eure Hilfe 👍
