### ISSUE TITLE
Installer not working

### ISSUE THREAD

**Issue by criskolkman** [First-Coder/TS3-Webinterface#77]
Hello,

I love the looks of this webinterface admin! Keep up the awesome work!

Unfortunately I cannot use it yet, because the installer won't work.
After testing the database I click the button "Create Database", and the text "Creating..." is being shown in the Console area.
But... nothing happens, the database is not being created nor any error is visible.

What could be the problem here?

**Comment by Sebbo94BY** [comment]
The referenced issue is about the same topic like yours - just in German.

There is no solution yet.

**Comment by criskolkman** [comment]
I'm getting these errors:

> [Tue Nov 21 12:23:58.447551 2017] [fcgid:warn] [pid 16584] [client 1.2.3.4:62283] mod_fcgid: stderr: PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[28000] [1045] Access denied for user 'c2mm'@'localhost' (using password: YES)' in /var/www/clients/client2/web5/web/install/functionsPost.php:228, referer: http://mydomain.com/index.php
[Tue Nov 21 12:23:58.447583 2017] [fcgid:warn] [pid 16584] [client 1.2.3.4:62283] mod_fcgid: stderr: Stack trace:, referer: http://mydomain.com/index.php
[Tue Nov 21 12:23:58.447587 2017] [fcgid:warn] [pid 16584] [client 1.2.3.4:62283] mod_fcgid: stderr: #0 /var/www/clients/client2/web5/web/install/functionsPost.php(228): PDO->__construct('mysql:host=loca...', 'c2mm', 'PASSWORD'), referer: http://mydomain.com/index.php
[Tue Nov 21 12:23:58.447589 2017] [fcgid:warn] [pid 16584] [client 1.2.3.4:62283] mod_fcgid: stderr: #1 {main}, referer: http://mydomain.com/index.php
[Tue Nov 21 12:23:58.447592 2017] [fcgid:warn] [pid 16584] [client 1.2.3.4:62283] mod_fcgid: stderr:   thrown in /var/www/clients/client2/web5/web/install/functionsPost.php on line 228, referer: http://mydomain.com/index.php

**Comment by criskolkman** [comment]
@Sebi94nbg Ah thanks, I didn't see that one because my German is not that awesome.
Any ideas on when this should be fixed?
Do you need any more information from my side to help solve this problem?

**Comment by Sebbo94BY** [comment]
Well... The [line 228 of /install/functionsPost.php](https://github.com/First-Coder/TS3-Webinterface/blob/1.3.14-OPEN-BETA/install/functionsPost.php#L228) fails due of wrong credentials.

I believe, the required parameters are just empty or wrong. @lgund you're "enoding" the URI component in [/install/index.js#L202-L209](https://github.com/First-Coder/TS3-Webinterface/blob/1.3.14-OPEN-BETA/install/index.js#L202-L209). Does this may cause the issue? You know your code better then everyone else. ;)

@criskolkman if you want to, you can just `var_dump()` the variables before they are used for the PDO connection. Just add the following code to the line above the mentioned line, which causes the issue:
https://github.com/First-Coder/TS3-Webinterface/blob/1.3.14-OPEN-BETA/install/functionsPost.php#L227
```
echo "DEBUGGING<br>";
echo "<br>STRING:<br>";
var_dump($string);
echo "<br>USER:<br>";
var_dump($_POST['user']);
echo "<br>PASSWORD:<br>";
var_dump($_POST['pw']);
echo "<br>END DEBUGGING";
```
After adding this, please save the file and execute your failed step once again. You should now see some further outputs. Please provide the output to us.

**Note:** Please censor the printed password with the text "CENSORED". But verify, if it's the correct one.

**Comment by criskolkman** [comment]
@Sebi94nbg Adding that code to the file functionsPost.php does not make it echo anything :)

**Comment by lgund** [comment]
The problem is, that the functionPost will be opened with a Ajax request. You need to make it with a console.log command.

But I will today check this issue and will inform you, if I found something. I will also upload the installer for v2. It’s not tested yet but it should be work much better then the current.

Dear 
Lukas 

@Sebi thanks for your support

**Comment by criskolkman** [comment]
Okay I found the problem.
The password I used for the MySQL connection was not being accepted, so there's something wrong in the code with that.
I changed the password to a new password without any special characters, and now the installation is successful.

@lgund This is probably something that needs to be checked? :)

**Comment by lgund** [comment]
Looks like I missed to decode the uri.... I will check that today :)

**Comment by criskolkman** [comment]
@lgund Great, it seems that it is not accepting the @ in the password.
In the first phase (when checking the db connection) all is fine, but when you create the database, the "wrong" password is being used because the @ is being replaced by the following:

%40

**Comment by lgund** [comment]
I´ve found the bug and ye it´s right. The url encoded string will not be decoded if he create the database. I am currently trying to upload the updated installer zip. This may take a while, cause I´ve no DSL connection. But it will be updated in the next hours!

PS Updated on 21.11.2017 17:28 (German time xD)
