### ISSUE TITLE
jquery timer ( fadeout/in ) zu lang / groß

### ISSUE THREAD

**Issue by osnet** [First-Coder/TS3-Webinterface#8]
kann man den timer da etwas runtersetzen ? irgendwie ist das bissl uebertrieben lang.

**Comment by lgund** [comment]
Meinst du den preloaded ?

**Comment by osnet** [comment]
den sehe ich nur beim ersten mal seite laden,  
ich meine  das   laden der unter seiten, 
da klickste auf einen link  dann faded die  alte seite  leicht aus und die neue kommt,  
aber irgendwie  etwas lahm. 
Oder taeuscht das ?

**Comment by lgund** [comment]
Habe da slow drinne stehen, werde das auf fast ändern. Danke für den tipp :)

**Comment by lgund** [comment]
Habe es auf fast geändert, geht nun sehr schnell ;)

**Comment by ghost** [comment]
> Habe es auf fast geändert, geht nun sehr schnell ;)

Kannst vielleicht sagen was wo du geändert hast? Würde das gerne jetzt schon einstellen. Dieser Fadeeffekt ist zwar schön aber einfach lahm. Ist meine persönliche Meinung, andere sehen das ganze wieder anderst. ;)

**Comment by lgund** [comment]
Das Update wird heute kommen...

Falls du wirklich nicht bis heute Abend warten kannst, so schaue mal in die main.js, sowie teamspeak.js unter /js/webinterface/

**Comment by ghost** [comment]
Na klar kann ich warten. Konnte aber sein das Du alles was jetzt hier angefragt worden ist erstmal in Ruhe fertig machen willst und dann das Update erst raus schickst. Deshalb fragte ich nach.

**Comment by lgund** [comment]
Das ist richtig, bloß momentan funktioniert das Interface so gut wie gar nicht. Nicht mal der Teamspeakviewer wird angezeigt. Es sollte min. Alles angezeigt werden, daher das schnelle Update heute. Danach wird erstmal gesammelt....

**Comment by ghost** [comment]
> Nicht mal der Teamspeakviewer wird angezeigt.

Okay kann ich so nicht bestätigen, wie du gesehen hast auf meiner Seite wird er angezeigt. Das einzige was eine Lösung braucht wenn die Channelnamen zu lang sind oder man eine grössere Fontgrösse benutzt, das diese gekürzt werden.

**Comment by lgund** [comment]
>  Das einzige was eine Lösung braucht wenn die Channelnamen zu lang sind oder man eine grössere Fontgrösse benutzt, das diese gekürzt werden.

Gibt es dafür eine genauere Fehlerbeschreibung :D

**Comment by ghost** [comment]
> Gibt es dafür eine genauere Fehlerbeschreibung :D

Fehler ist es ja nicht. 

So Screen 1 zeigt den Teamspeakviewer mit zu langen Channelnamen und größerer Fontgröße.

![e092426a-e15c-11e6-97f7-558c7ada9dfb](https://cloud.githubusercontent.com/assets/24642274/22245816/3507527e-e232-11e6-8216-b3e75897fd48.png)

So Screen 2 zeigt kürzere Channelnamen und kleinere Fontgröße.

![2017-01-24- 1](https://cloud.githubusercontent.com/assets/24642274/22245852/57d21e9c-e232-11e6-98b1-8ce05bd0ec5e.png)

Das man da vielleicht eine flexiblere Lösung findet.

**Comment by lgund** [comment]
> Das man da vielleicht eine flexiblere Lösung findet.

Falls jemanden dort eine andere Lösung einfällt. Ich persönlich sehe das nicht als Bug. Man muss es eben richtig einbetten :)
