### ISSUE TITLE
Logs Sortierung 

### ISSUE THREAD

**Issue by Provokan** [First-Coder/TS3-Webinterface#80]
Guten Tag, 

Kurze Frage bezüglich der Logs, für mich macht es keinen Sinn das die ältesten Log Einträge als erstes angezeigt werden, daher ein Ideen Vorschlag. Ist es möglich die neusten Einträge immer als erstes anzeigen zulassen, wenn nicht sogar ein Suchfeld einzufügen um sich die Logs eines bestimmten Datums ausgeben zu lassen ? 

Zudem steht bei mir unter Systemlogs " Logdatei ist noch nach dem alten Stand. Bitte leeren Sie den Log manuell!"  Jedoch ist die Datei leer, wie kann man das beheben ?

**Comment by Provokan** [comment]
Sehe grade, dass es ein Suchfeld bereits existiert.

**Comment by lgund** [comment]
Da wird es eher ein bug sein. Ich glaub ich habe die Überprüfung, ob die datei leer ist vergessen einzubauen. Ich werde es demnächst prüfen!

Sollte ich zudem noch die die sortierung der Einträge umkehren oder reicht das suchfeld?

**Comment by Provokan** [comment]
Ich denke es ist für alle einfacher wenn die aktuellsten Einträge an erster Stelle sind.

**Comment by Sebbo94BY** [comment]
Ein kurzes Feedback von mir: In Log-Dateien sollten die aktuellsten Einträge immer am Ende der Datei stehen. In Anwendungen genau anders rum - die aktuellsten ganz oben, also am Anfang. :)

Warum bei Log-Dateien die neuesten unten? `tail -f error.log` zeigt immer die letzten Zeilen und die dazukommenden an. Dementsprechend müssen Einträge auch unten angehängt werden. ;)

In einer Anwendung will aber kein Admin jedesmal auf die letzte Seite oder nach ganz unten springen, um die aktuellsten Einträge zu sehen. Er erwartet sie ganz oben. :)

**Comment by lgund** [comment]
Kann ich verstehen, wird überarbeitet :)

**Comment by lgund** [comment]
Ab heute in der 1.3.16 behoben 👍
