### ISSUE TITLE
Webinterface Version

### ISSUE THREAD

**Issue by Provokan** [First-Coder/TS3-Webinterface#81]
Servus, 

ich habe gesehen dass die 1.3.15 bereits seit längerer Zeit draussen ist, 
ab wann können wir mit der hier auf Github bzw wann können wir unsere Interface 
damit updaten? (: 

Wünsche euch noch ein Guten Rutsch (:

**Comment by lgund** [comment]
Es befindet sich beim updater leider noch ein bug. Bitte rufe einfach den updater manuell auf über /updater/updater.php . Dort sollte es möglich sein, auf die letzte version zu updaten :)

**Comment by Provokan** [comment]
Alles klar  (: Danke 

#closed
