### ISSUE TITLE
Localization not work

### ISSUE THREAD

**Issue by alsoGAMER** [First-Coder/TS3-Webinterface#82]
I write the localization file it.php, i've uploaded It into /panel/lang, selected with lang.php file and when i've reloaded the page it's show blank entries, only the icon!

**Comment by lgund** [comment]
Is it possible to get the file? I would add the language to the interface with you as Autor and could help you if something is wrong with the file.

**Comment by alsoGAMER** [comment]
Ok @lgund i'll send you the file. Please give me an your contact on telegram if you have or your email

**Comment by alsoGAMER** [comment]
Ok, @lgund. Which site to upload the file?

**Comment by lgund** [comment]
Just send it me to admin@first-coder.de

**Comment by alsoGAMER** [comment]
Ok, what subject?

**Comment by lgund** [comment]
I got the file... I will check it in the next hours...

**Comment by alsoGAMER** [comment]
Ok, thanks. But (if for u isn't a problem) contact me with email.

**Comment by lgund** [comment]
I´ve found a lot of syntax problems. I´ve fixed them and it would be nice if you could finish the italian translation. The problem you had was the ' sign. You need to use the html syntax for it. That mean you would write &apos; instead of '. You can find a list of html syntax here in the table;
[http://wiki.selfhtml.org/wiki/Referenz:HTML/Zeichenreferenz](http://wiki.selfhtml.org/wiki/Referenz:HTML/Zeichenreferenz)

Just change the it.txt into it.php again. After that upload it and it should be work.
[it.txt](https://github.com/First-Coder/TS3-Webinterface/files/1619254/it.txt)

**Comment by alsoGAMER** [comment]
Ok, thanks for your check. I'll made the changes now

**Comment by alsoGAMER** [comment]
I've uploaded the file you send to me but the bug isn't fixed. Only "icon", no text

**Comment by alsoGAMER** [comment]
![screen](https://user-images.githubusercontent.com/35269770/34781467-3059615a-f626-11e7-8cf5-d905d375ff57.png)

**Comment by alsoGAMER** [comment]
I've added `$language = array();
$installedLanguages = array(

"german" => "First-Coder.de",
"english" => "cjmwid",
"italian" => "alsoGAMER");` 

in file stored in /panel/lang/lang.php, select them with the settings of the interface and now the panel show the entries, but are in english.... And if i select "english" as language with the interface it's buggy all another times

EDIT: I've made test and i notice that the panel continuing reading en.php file despite i've selected the italian language in lang.php file, this is a very serious bug! Please @lgund flag this issues as bug an resolve this ASAP

**Comment by lgund** [comment]
That´s strange, cause in my version everything works well. Please download the zip file and replace all the files. Maybe there is just some small syntax error.

[lang.zip](https://github.com/First-Coder/TS3-Webinterface/files/1619741/lang.zip)

**Comment by alsoGAMER** [comment]
I doing test from 1 hour to now with my raspberry.. holding on :/

**Comment by lgund** [comment]
Just let us know if it’s work

**Comment by alsoGAMER** [comment]
I'm not home atm.. i'll try tomorrow if i haven't too much things to do

**Comment by alsoGAMER** [comment]
@lgund After 4 days of testing the localization works!! I've uploaded them to powerofspeak.tk/betatest, seleting them and works!!!! Finally :)

**Comment by alsoGAMER** [comment]
I have to make a note.. the translation in English is very bad... missing pieces, incorrect translations, typos, and much more.. I suggest you change the translator..

**Comment by alsoGAMER** [comment]
Here the file.. butw the panel won't read all the translation from this file.... (again)
[it.txt](https://github.com/First-Coder/TS3-Webinterface/files/1629549/it.txt)

**Comment by lgund** [comment]
You don’t know how hard it is to get a good and free translator. I will upload the new language in the next update.

**Comment by alsoGAMER** [comment]
@lgund if u want i can help u with the eng translation :)

**Comment by lgund** [comment]
If you wanna update them you are free to use it. I could upload them and add your name as autor.

**Comment by alsoGAMER** [comment]
And we are!! It was enough easy! Complete code check and removal of syntax errors.. 
time required: about 20/30 minutes :) [en.txt](https://github.com/First-Coder/TS3-Webinterface/files/1638152/en.txt)

**Comment by alsoGAMER** [comment]
If u want me for other jobs, contact me with email.. for the localization no problem, i update them asap when u get published the german localization! :) Happy to help make the interface better

**Comment by lgund** [comment]
If fixed now the problems in the lang file and will today make a new update with the new files 👍
