### ISSUE TITLE
Can't use gmail smtp for automatic mail service!

### ISSUE THREAD

**Issue by alsoGAMER** [First-Coder/TS3-Webinterface#85]
The interface returns an error with the login on gmail smtp server during the configuration!

**Comment by lgund** [comment]
Sorry for answering so late....

The smtp framework is not written by myself. Normaly it should easy work. If it returns a error maybe you can tell us the error?

**Comment by alsoGAMER** [comment]
A strange error with configuration

Il sab 10 feb 2018, 4:51 PM First-Coder <notifications@github.com> ha
scritto:

**Comment by alsoGAMER** [comment]
EDIT: With auth*

Il sab 10 feb 2018, 6:53 PM alsoGAMER <notifications@github.com> ha scritto:

**Comment by lgund** [comment]
Can you please send the error details?

**Comment by alsoGAMER** [comment]
No, because i have problem with php and i can't login the interface

**Comment by lgund** [comment]
Which problem with php?
