### ISSUE TITLE
Instanz wird im Webinterface nicht angezeigt

### ISSUE THREAD

**Issue by Tiiiimo** [First-Coder/TS3-Webinterface#86]
Hey,
ich habe das folgende Problem.. 
ich habe eine Instanz erfolgreich erstellt, aber der Server wird im Dashboard nicht angezeigt.
Ich kann aber mit dem Pfad "http://IP/webinterface/index.php?web_teamspeak_serverview?0?1"
direkt drauf zugreifen, kann auch zb Channel erstellen, aber der Bot connectet kurz auf den Ts und leavet dann wieder.

Screenshot: https://picload.org/view/daagcriw/desktop25-02-201819-51-13-709.png.html

**Comment by lgund** [comment]
Wenn du direkt auf dem Server bist und dort Channel erstellst oder andere Aktivitäten im teamspeak machtet, können diese dann auch erfolgreich durchgeführt werden? Oder kommt ein Connection lost ?

**Comment by Tiiiimo** [comment]
@lgund Diese können ausgeführt werden

**Comment by lgund** [comment]
@SoulofSorrow should check that if that´s ok for you?

**Comment by Tiiiimo** [comment]
@lgund Habt ihr schon was rausbekommen?

**Comment by lgund** [comment]
Gibt es eine Möglichkeit Zugang zum Interface zu bekommen? Ich vermute man müsste sich das genau anschauen...

**Comment by Tiiiimo** [comment]
@lgund Klar Email: Admin@EnjoyPvP.net Password: Admin123

**Comment by lgund** [comment]
Schreib mir am besten eine Mail mit den Daten. Mir fehlt noch die Adresse zum Interface :)

**Comment by lgund** [comment]
So habe mich gerade mal eingeloggt und auf den "Fehler" gefunden. Dein Queryclient hat keinerlei Rechte und kann daher auch nicht wirklich etwas mit den Informationen machen. Er hat leider nicht mal Rechte die vorhanden Serverinformationen abzufragen. Wenn man unter Instanz in der Konsole serverlist eingibt kommt folgende Meldung:

> ErrorID: 2568 | Message: insufficient client permissions failed_permid=4

Entweder du verwendest hier den serveradmin Account, der beim erstellen des Teamspeakservers vergeben wird oder erstellst ein Queryaccount der die notwendigen Rechte besitzt.

**Comment by Tiiiimo** [comment]
@lgund Meine Instanz auf der ich den Queryaccount erstellt habe, hat Adminrechte, daran kann es nicht liegen. Ich benutze ja auch andere Sachen wie zb Rankingsystem und das braucht auch ein Queryaccount.

Außerdem werden ja auch alle Befehle ausgeführt. Nur der Bot connectet nur für ein kurzen Moment und dann disconnectet er wieder.
Sag mir doch mal welche Rechte der benötigt, aber eigentlich hat dieser Account alle Rechte

**Comment by lgund** [comment]
@Tiiiimo Leider kann ich dir nicht genau eine Liste geben welche Rechte das Interface benötigt. Es kommt ganz darauf an, was du im Interface machen willst. der Fehler der oben beschrieben wurde kann in [dieser](https://www.tsviewer.com/index.php?page=faq&id=12&newlanguage=de) Liste nachvollzogen werden. Ich habe dort einfach nur die serverliste von deiner instance abfragen wollen. Damit das geht benötigt der Querybenutzer die Rechte `b_serverinstance_virtualserver_list`.

**Comment by Tiiiimo** [comment]
@lgund Ich habe alle Rechte vergeben. Es funktionert ja alles, aber möchte das dieser Server auch im Dashboard angezeigt wird, dies ist aber nicht der Fall. Dort gibt es doch bestimmt etwas was man da noch beachten muss damit das funktioniert. Du hast es ja schließlich programmiert.

**Comment by lgund** [comment]
> ErrorID: 2568 | Message: insufficient client permissions failed_permid=4

@Tiiiimo  dieser Fehler meldet, dass der Nutzer eben nicht ausreichend Rechte besitzt. Auch wenn ich das Interface entwickelt habe kann ich nichts dagegen unternehmen, dass dein Queryaccount nicht genügend Rechte besitzt.

**Comment by Tiiiimo** [comment]
@lgund ok trotzdem danke für deine Hilfe.
