### ISSUE TITLE
Installation bleibt stehen

### ISSUE THREAD

**Issue by erfurtjohn** [First-Coder/TS3-Webinterface#89]
Beim installieren der Software bleibt die Installation beim letzten Schritt einfach hängen. Es wird kein Benutzer oder sonstiges angelegt und in der Konsole wird weiterhin einfach nur "Creating" angezeigt.

Die Tabellen aus dem vorherigen Schritt wurden allerdings bereits angelegt.

Was kann falsch laufen, oder besser gesagt, ist ein ähnlicher Fall schon einmal aufgetreten?

**Comment by lgund** [comment]
Tatsächlich ist so ein ähnlicher Fall schon mal aufgetreten. Ich hatte es aber im Installer eigentlich behoben gehabt. Bitte sei dir sicher das du unter [First-Coder](https://first-coder.de/) die aktuellste Version heruntergeladen hast. Wenn dann immernoch der Fehler auftritt, wäre es gut wenn du (nur für die installation) ein einfaches Datenbankpasswort verwendest. Es gab beim Installer das Problem das Sonerzeichen nicht richtig umgewandelt wurden und daher das Script nichts erstellen konnte.

Du kannst am nachhinein das Passwort in der config/config.php wieder auf ein sicheres ändern.

@PS ich denke wenn du den Installer direkt von meiner Seite verwendest sollte das Problem nicht mehr auftreten!

Mfg
Lukas

**Comment by lgund** [comment]
Konnte der Fehler damit behoben werden? Falls nein öffne diesen Post bitte wieder....
