### ISSUE TITLE
TicketSystem

### ISSUE THREAD

**Issue by osnet** [First-Coder/TS3-Webinterface#9]
Tickets werden nicht gelöscht,  nicht mal vom SuperHeftigServeradmin.
nur geschlossen.  ggfs  archiviert und ausgeblendet,  aber nicht geschlossen. 
Der Supergau für jedes Monitoring ^^

**Comment by osnet** [comment]
Adminansicht Ticketsystem. 
Ist noch etwas unausgereift.  In der Übersicht sollte folgendes stehen
Ticket ID , Ticketgruppe, Betreffender Server, Priorität

Prio 1 : ASAP
Prio 2 : Bei Gelegenheit
Prio 3 : Internes Bugmanagement

Wäre etwas überzogen hier mit  Responsetimes zu arbeiten.  ausser das ding geht mal kommerziell, dann sollte das einkalkuliert werden.

**Comment by lgund** [comment]
> Tickets werden nicht gelöscht, nicht mal vom SuperHeftigServeradmin.
nur geschlossen. ggfs archiviert und ausgeblendet, aber nicht geschlossen.
Der Supergau für jedes Monitoring ^^

Das kann ich nicht bestätigen, habe es gerade mal getestet. Gibt es bei dir irgendwelche Fehler in den logs?

**Comment by osnet** [comment]
ich sollte lernen mich besser auszudrücken .... 
ich wollte eigentlich sagen,  die  tickets werden momentan gellöscht,  das soll aber  so nicht sein. 
somit kann man über die zeit hinweg nicht  protokollieren, was am haeufigsten aufgetreten ist,   wer  den meisten mist macht  etc ...    momentan werden die tickets  astrein aus der DB  rausgeschmissen. 
bitte das korrigieren.

**Comment by lgund** [comment]
Der Wunsch war damals sie auch löschen zu können. Ich denke mal ich werde einfach eine funktion einbauen die das löschen abschaltet.

Ps löschen kann sowieso nur ein ticketadmin

**Comment by lgund** [comment]
Ticket ID ist in der heutigen version dabei ;)

**Comment by lgund** [comment]
> Betreffender Server, Priorität

Wird das ganz sicher benötigt?

**Comment by osnet** [comment]
vorerst nicht,  lass das mal aber irgendwo auf ner todo liste : )

**Comment by lgund** [comment]
Ab der neuen version kann in der config.cfg eingestellt werden, ob es möglich ist, tickets aus der Datenbank zu löschen.
