### ISSUE TITLE
Migration syntax error on PSQL

### ISSUE THREAD

**Issue by ghost** [First-Coder/TS3-Webinterface#91]
## System Information
***Operating System:***
Arch Linux

***Operating System Type:*** (x86|x64)
x64

***Interface Version:*** (do not use generic words like "latest" or equal, insert the number)
1.3.17-STABLE

***PHP Version, MySQL Version, Apache Version:*** (do not use generic words like "latest" or equal, insert the number)
PHP 7.2.3
PSQL 10.3
NGINX 1.12.2

***TeamSpeak/TeaSpeak Server Version:***
3.1.1

## Issue
***Reason for reporting this issue:***
Need DB connection.

***Detailed Description:***

After connecting the database and trying to migrate, all tables cannot be created. When you really wanna support PSQL you have  to provide different migrations for it. int(11) is not a valid expression. The ID should be `int8`. This applies for other tables and types too. In general, why don't you use existing migration tools instead of producing nearly unreadable spaghetti code in the `functionsPost` file? [See how the Tiny Tiny RSS dev does it](https://github.com/major/tt-rss/tree/add-accept-headers/schema).

```
Create Table: 'ticket_answer'
    Table 'ticket_answer' could not be created :/
Error in Create Table 'main_clients_rights_server_edit'... delete the whole Table now that you can maybe Restart the process!
Error in Create Table 'main_modul'... delete the whole Table now that you can maybe Restart the process!
Error in Create Table 'main_clients'... delete the whole Table now that you can maybe Restart the process!
Error in Create Table 'main_clients_rights'... delete the whole Table now that you can maybe Restart the process!
Error in Create Table 'main_clients_infos'... delete the whole Table now that you can maybe Restart the process!

Error at Add Rights in 'main_rights'... delete the whole Table now that you can maybe Restart the process!


Error from Database: FEHLER: Syntaxfehler bei »(« LINE 2: id int(11) NOT NULL, ^
```

**Comment by lgund** [comment]
I am sure that the code in the functionsPost isn´t the best solution. But that will be just once executed and works normally very well. If you would change `id int(11) NOT NULL` to `id int(8) NOT NULL` I am sure the database will be created. You can find it on line 647. I will update the installer with the next version so we can support pgsql again.

If there are other sql syntax errors please let it me know.

**Comment by ghost** [comment]
Thanks for your reply. Having a real migration system makes things easier for you, was just a hint :-)

I think datetime should be timestamp etc. Hoping for the next version :+1:

**Comment by lgund** [comment]
I can’t really test it. Is it possible to get a pgsql database from you?

**Comment by ghost** [comment]
I think you can go with the following, although it is not tested:

```
CREATE TABLE ticket_answer
  (
     id        INT8 NOT NULL,
     ticketid  INT NOT NULL,
     pk        VARCHAR(40) NOT NULL,
     msg       TEXT NOT NULL,
     moderator TEXT NOT NULL,
     dateaded  TIMESTAMP NOT NULL
  );

CREATE TABLE ticket_tickets
  (
     id           SERIAL NOT NULL,
     pk           VARCHAR(40) NOT NULL,
     subject      TEXT NOT NULL,
     msg          TEXT NOT NULL,
     department   TEXT NOT NULL,
     status       TEXT NOT NULL,
     dateaded     TIMESTAMP NOT NULL,
     dateclosed   TIMESTAMP NOT NULL,
     dateactivity TIMESTAMP NOT NULL,
     PRIMARY KEY (id)
  );

CREATE TABLE main_mails
  (
     id           VARCHAR(100) NOT NULL,
     headline     VARCHAR(100) NOT NULL,
     mail_subject VARCHAR(255) NOT NULL,
     mail_body    TEXT NOT NULL,
     PRIMARY KEY (id)
  ); 
```

EDIT:

I tried installing it with this schema. Tables are being created.

The step after this produces an error (500).

php fpm output:

```
PHP message: PHP Fatal error:  Uncaught Error: Call to a member function errorInfo() on boolean in /srv/http/domain.tld/htdocs/ts3web/install/functionsPost.php:137
Mär 31 17:24:18 nginx[11556]: Stack trace:
Mär 31 17:24:18 nginx[11556]: #0 {main}
Mär 31 17:24:18 nginx[11556]:   thrown in /srv/http/domain.tld/htdocs/ts3web/install/functionsPost.php on line 137
```

If I comment in `errorInfo` it will take me to the next step but without a redirect. Manually deleting the `install/` folder works, but the main page index will tell me there is no database connection. The insert is not working and the config editing is also not working 100%.

If you like to support other databases, you should rewrite the entire install routine. Simplify it: just one file where admin types in db connection and initial user. Then something like `php install.php`. Delete this file afterwards. Done. Or if you like, a web interface for it. But this is more friendly code-wise and to debug. And you don't have to waste time to maintain the install things. They will just work. Best: use migration tool like phpmig.

Are all DB queries prepared statements? I didn't look at them entirely. So at least injections won't be a problem?

I would also think about using an ORM like eloquent or doctrine for your custom entities which are not related to ts3. Otherwise it might happen that you have to write extra lines of code for each "supported" database. ORM will just do that for you. It will ease developing.

I don't want to offend you, but your code is hardly readable at all. This begins at spacing, german variable names etc. You really have to refactor it. Take this as a hint for further projects. I also think that the "stable" git tag is completly misleading. It is not stable at all. At least this holds true for the install routine. It's not robust and I think that it wasn't tested. You might also consider using docker and docker-compose to test different environments fast (like psql).

PS: A config option for disabling sending usage data to your server is also the correct way in the future. Otherwise you have to deal with german law in May. "AGB" are not enough. The new law forces that you provide an option to completly disable it or at least explicitly list when, what and why data is being sent and why the app needs it and a reason why it would not function without it.

PPS: Can you also provide a version without using CDNs? [This might be interesting if you didn't knew it already.](https://www.kuketz-blog.de/kommentar-datenschutz-auf-webseiten-quo-vadis/)

PPPS: Sorry for the long post. :+1:

**Comment by lgund** [comment]
First of all thanks for the feedback. I know what you want to tell me but in v1 it will not be rewritten cause I am currently finishing the last steps of v2. I will update v1 so that pgsql will be work successfull and in v2 I will make it better 👍 . 

> Are all DB queries prepared statements? I didn't look at them entirely. So at least injections won't be a problem?

All Information where the user has a input field will be prepared to be secure for sqli.

> I don't want to offend you, but your code is hardly readable at all. This begins at spacing, german variable names etc. You really have to refactor it. Take this as a hint for further projects

That´s strange. I tried to comment all lines and the spaces looks fine in my editor. I am using notepad++. But the Teamspeak Control that I am also curring working will be more userfrindly cause I am using there vs code with there documentation comments.

> A config option for disabling sending usage data to your server is also the correct way in the future. Otherwise you have to deal with german law in May. "AGB" are not enough. The new law forces that you provide an option to completly disable it or at least explicitly list when, what and why data is being sent and why the app needs it and a reason why it would not function without it.

That´s true. This option was just removed cause it will just give you a hint of a newer version. There will be no user data sended.

**Comment by ghost** [comment]
Ok :+1: 

I did implement my own simple interface [(ts3web)](https://github.com/varakh/ts3web). So you don't have to add support for PSQL just for me. Maybe it is easier to drop PSQL support entirely for the old version.

Greetings
varakh

PS: I will close this.
