### ISSUE TITLE
Userbann

### ISSUE THREAD

**Issue by derrobin154** [First-Coder/TS3-Webinterface#93]
## System Information
***Operating System: Windows***

***Operating System Type: x64*** (x86|x64)

***Interface Version: lastest*** (do not use generic words like "latest" or equal, insert the number)

***PHP Version, MySQL Version, Apache Version: lastest (from Plesk)*** (do not use generic words like "latest" or equal, insert the number)

***TeamSpeak/TeaSpeak Server Version: none***

***Web Browser and this version: Firefox, lastest***

## Issue
***Reason for reporting this issue:***
Fehler bei Benutzersperrung

***Detailed Description:***
Wenn ich einen Benutzer bis zu einem Datum sperre, speichert sich die Sperrung aber nicht das Datum.

**Comment by derrobin154** [comment]
Aufgefallen, ist mir das übrigens auch bei den Benutzerrechten, dort speichert er auch nicht das Datum

**Comment by lgund** [comment]
Hallo,
ich kann denn Fehler bei mir leider nicht feststellen. Welche Version des Interfaces verwendest du denn? Gibt es die Möglichkeit einen testzugang zu erhalten? Denn kannst du mir per pm via skype unter lukas-1450 schicken oder per mail an admin@first-coder.de.

Gibt es irgendwelche Meldungen in den Interface system logs?

**Comment by derrobin154** [comment]
Ich benutze die neuste Version die es bei first-coder zum Download gibt.

das system.log gibt mir folgendes aus: 
"2018-04-07 22:36:05	|		ERROR		|	userEdit (SQL Error):Unknown column 'NaN' in 'field list'
2018-04-07 22:36:08	|		ERROR		|	userEdit (SQL Error):Unknown column 'NaN' in 'field list'
"

**Comment by lgund** [comment]
Okey hierbei scheint es sich um einen fiesen bug zu handeln der schon mehrfach aufgetaucht ist... Ich selbst könnte ihn nie nach replizieren und würde mir daher wünschen, dass wir ihn zusammen beheben können.

Problem
===========
Ich weiß bisher das aus irgendeinem Grund JavaScript den datetimepicker nicht richtig abfragen kann und statt dem timestamp nur NaN = Not a Number zurückgibt, welcher dann so in der Datenbank abgelegt wird. Das Interface kann natürlich mit NaN nichts anfangen und gibt dem entsprechend ein Fehler aus.

Lösungsansatz
============
Es gibt zwei Möglichkeiten:
1. Du versuchst den Fehler rauszufinden, falls du dich mit php und JavaScript auskennst und ich versuche dir per Ferndiagnose zu helfen.

2. du erstellst ein für Account der mir rechte in den Ordnern /php und /ja gibt sowie ein Interface Account um den Fehler zu erstellen. Des weiteren würde ich ein sql Account benötigen um in die Datenbank schauen zu können.

Ich würde die selbstverständlich keine Nutzerzahlen ändern o.ä.. Zugangsdaten zu Datenbank, sowie teamspeak sind im config Ordner auf dem ich kein Zugang hätte, weswegen da kein Risiko besteht. Falls du dich dazu entscheidest mir temporär die Daten zu geben sende sie per Skype an lukas-1450 oder per Mail an admin@first-coder.de.

Mit freundlichen Grüßen 
Lukas

**Comment by lgund** [comment]
Gibt es hier schon ein Fortschritt?

**Comment by lgund** [comment]
Ok ich habe eine Lösung zu diesem Problem gefunden. Es wird in der kommenden Version gefixt werden. Allerdings kann es auch manuell hierüber getan werden.

Fix
==========
Einfach den Inhalt des .zips mit dem bestehenden überschreiben.
[Interface.zip](https://github.com/First-Coder/TS3-Webinterface/files/1926992/Interface.zip)
