### ISSUE TITLE
[Wunsch] Rechte beantragen

### ISSUE THREAD

**Issue by derrobin154** [First-Coder/TS3-Webinterface#94]
Moin,
Es wäre super wenn eingefügt wird dass man sich auch Benutzerrechte beantragen kann.

Grüße

**Comment by lgund** [comment]
Inwiefern stellst du dir das vor? Meinst das ein Nutzer alle Rechte des Interfaces einsehen kann und daraus eine Liste erstellt, welche er gerne haben möchte?

**Comment by derrobin154** [comment]
Es gibt ja für den Benutzer eine Rechte übersicht welche er besitzt und welche nicht, und neben dem Recht das er nicht besitzt soll ein Button sein wo der User das Recht beantragen kann.

**Comment by lgund** [comment]
Okey und wo soll diese auftauchen? Soll der Admin ein extra Menüpunkt haben mit rechtewünsche?

**Comment by Provokan** [comment]
Sorry, das ich mich da einklinge, aber ich denke es ist nicht produktiv, alles systematisch einzubinden. 
Es existiert ja bereits ein Ticket system, dort kann man auch einfach ein Ticket eröffnen wo der jenige
die notwendigen Rechte "beantragen" kann. Dies auch evtl. begründen kann wieso und weshalb.
